### ISSUE TITLE
Strip shebang from .js files

### ISSUE THREAD

**Issue by nhz-io** [rollup/rollup-plugin-commonjs#102]
## Presence of shebang in `.js` files will break the bundling
```
Message:
    Error transforming .../node_modules/rc/index.js with 'commonjs' plugin: 
        Unexpected character '#' (1:0) in .../node_modules/rc/index.js
```

### Culprit: https://github.com/dominictarr/rc/blob/master/index.js#L1
```js
#! /usr/bin/env node
var cc   = require('./lib/utils')
var join = require('path').join
...
```

**Comment by aedart** [comment]
Was there any solution to this issue?

Currently I do have the same problem when attempting to run a few tests using karma, rollup preprocessor and this plugin.

In other words, how did you "patch" (#103) whatever module you had this problem with?

**Comment by kaosat-dev** [comment]
Hello @nhz-io  & @aedart same question, I have a few CLI programs that need the shebang, manually adding it back is not really an option, how did you end up solving this ?

**Comment by nhz-io** [comment]
There, we solved it similar to the way that is in this sample repo: https://github.com/nhz-io/infra.strip-shebang
