### ISSUE TITLE
v4 breaks use with Marko Widgets

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup-plugin-commonjs#104]
I use [marko-widgets](https://github.com/marko-js/marko-widgets), but as of v4 of this plugin i can no longer use it with rollup. It seems some require calls become undefined.

The error that is shown in the console points towards a dynamic require, which i know will not work in rollup, but the actual error occurs earlier. that dynamic require should never be reached.

sorry i am tired, but I created an example at https://github.com/lohfu/rollup-marko-example

**Comment by patrick-steele-idem** [comment]
Just to clarify. This is not due to a dynamic require but rather a circular dependency. More details can be found in the following issue: https://github.com/rollup/rollup-plugin-commonjs/issues/105

**Comment by Rich-Harris** [comment]
Reply on #105
