### ISSUE TITLE
v5 breaks modules which assign reserved keywords to module.exports

### ISSUE THREAD

**Issue by leeyeh** [rollup/rollup-plugin-commonjs#110]
Upgrading to v5.0.3 from v4 breaks build:

```
SyntaxError: /home/travis/build/leancloud/js-realtime-sdk/node_modules/axios/lib/axios.js: Unexpected token (55:4)
  53 | 
  54 | // Allow use of default import syntax in TypeScript
> 55 | var default = axios;
     |     ^
  56 | 
  57 | export default axios_1;
  58 | export { axios_1 as __moduleExports };
```

The [source code of axios](https://github.com/mzabriskie/axios/blob/v0.14.0/lib/axios.js#L46) looks like:

```
// Allow use of default import syntax in TypeScript
module.exports.default = axios;
```

**Comment by Rich-Harris** [comment]
Hey @leeyeh, I think this is the same as https://github.com/rollup/rollup-plugin-commonjs/issues/112 which was just fixed – can you try the latest version and see if it's 👍 ? Thanks

**Comment by lxe** [comment]
Same things with "delete" and other reserved keywords

**Comment by audan2009** [comment]
Having a similar issue...

**Comment by youzi** [comment]
I'm having a similar issue with a dependency defining: `exports.static = function () {}`

`Error parsing x: The keyword 'static' is reserved (23:4) in x`

I'm using v ^5.0.5

**Comment by youzi** [comment]
Ok so seems to be an Acorn issue. I was able to work around this by passing options to Acorn: https://github.com/rollup/rollup/issues/564

**Comment by Rich-Harris** [comment]
This is the same issue as #116, I think – have just released 6.0.0 with a fix. Let me know if you still have problems, thanks

**Comment by mortargrind** [comment]
This is broken in version 7.0.0. When you try to `import axios from 'axios';`, you'll get `Error: Duplicate export 'default'`. When you delete `module.exports.default = axios;` line in the "node_modules/axios/lib/axios.js", it will compile (I don't know if the output will be correct, i have other errors :) ) Acorn option `allowReserverd: true` does not solve this.

**Comment by lukasjuhas** [comment]
I'm having same problem @mortargrind. Thanks for the tip, it does work if I comment out / delete that line.

**Comment by leeyeh** [comment]
I can confirm it's still broken for the keyword `default`: https://travis-ci.org/leancloud/js-realtime-sdk/builds/190498378#L1205

I can file a new issue if preferred. @Rich-Harris

**Comment by Rich-Harris** [comment]
I *think* this will have been fixed by https://github.com/rollup/rollup-plugin-commonjs/pull/173 — could you try installing the latest version to see? Thanks, sorry for the delayed response

**Comment by leeyeh** [comment]
Confirmed. Thank you.
