### ISSUE TITLE
module.exports.property failure

### ISSUE THREAD

**Issue by Qard** [rollup/rollup-plugin-commonjs#112]
It seems assigning an object to `module.exports` and then assigning a property on `module.exports`, rather than directly on that object will not attach it to 
that object.

see: https://github.com/maxogden/yo-yo/pull/48#issuecomment-247868137

**Comment by Rich-Harris** [comment]
Oh, CommonJS. Always finding new and exciting ways to make life difficult... Thanks, this is fixed in 5.0.4
