### ISSUE TITLE
module.exports = { foo: 'bar' } fails to create named exports and results in "does not export foo" error .

### ISSUE THREAD

**Issue by lxe** [rollup/rollup-plugin-commonjs#115]
Consider the following commonjs module:

``` javascript
// mycjsmodule.js
module.exports = {
   foo: 'bar'
};
```

If I attempt to do...

``` javascript
import { foo } from './mycjsmodule';
console.log(foo);
```

...rollup will produce the following error:

```
Module /mycjsmodule.js does not export foo (imported by /entrypoint.js)
```

Looks like the module gets transpiled into: 

``` javascript
var mycjsmodule = {
  foo: 'bar'
}

export default mycjsmodule;
export { mycjsmodule as __moduleExports };
```

However, if I do `module.exports.foo = 'bar'`, this error does not occur. The transpiled code is:

``` javascript
var foo = 'bar';

var mycjsmodule = {
    foo: foo
};

export default mycjsmodule;
export { mycjsmodule as __moduleExports };
export { foo };
```

Many commonjs exports utilize the `module.exports = { ... }` pattern, and each property in the module.exports object should be properly transpiled to a named export.

---

This specifically affects the [React npm module ](https://unpkg.com/react@15.3.2/lib/React)which exports all of its named exports as properties on an object that gets later assigned to `modules.exports`:

``` javascript

var React = {
...
 Component: ReactComponent,
...
}

module.exports = React;
```

This makes the following common code fail:

``` javascript
import React, {Component} from 'react';
```

**Comment by timdp** [comment]
With version 5.0.4, I'm seeing the same issue with [rx.disposables](https://github.com/Reactive-Extensions/rx.disposables/blob/07d5df25ae10e4dfea17da7d98f809e394f0a3ba/index.js). It doesn't occur anymore after downgrading to 4.1.0.

**Comment by FredyC** [comment]
Same issue with `redux-tcomb`
```
module.exports = {
  t: require('tcomb'),
  createCheckedMiddleware: require('./lib/createCheckedMiddleware'),
  createCheckedReducer: require('./lib/createCheckedReducer'),
  createActionType: require('./lib/createActionType')
};
```

> Error: Module D:\workspace\behavior3-chief\node_modules\redux-tcomb\index.js does not export createCheckedReducer (imported by D:\workspace\behavior3-chief\src\core\ReduxStore.js)

**Comment by Rich-Harris** [comment]
Apologies for the delay. More recent versions of Rollup will give you a more helpful error message pointing to this page: https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Essentially, you need to use the `namedExports` option documented on the [README](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports).

**Comment by DanielJoyce** [comment]
NamedExports doesn't work in all cases.
