### ISSUE TITLE
exports and variables become undefined in v4 and v5 (including v5 generating warnings in react)

### ISSUE THREAD

**Issue by lohfu** [rollup/rollup-plugin-commonjs#118]
When running v5 of the commonjs plugin i have started getting this error/warning in react:

```
Warning: Exception thrown by hook while handling onBeforeUpdateComponent: ReferenceError: validateProperty is not defined
ReferenceError: validateProperty is not defined
```

Calling `$ ag validateProperty` in my node_modules shows the call is made on the following lines in react:

```
react/dist/react.js
9882:  var validateProperty = function (tagName, name, debugID) {
9919:    var isValid = validateProperty(element.type, key, debugID);

react/dist/react-with-addons.js
10224:  var validateProperty = function (tagName, name, debugID) {
10261:    var isValid = validateProperty(element.type, key, debugID);

react/lib/ReactDOMUnknownPropertyHook.js
39:  var validateProperty = function (tagName, name, debugID) {
76:    var isValid = validateProperty(element.type, key, debugID);
```

This is the 4th or 5th occurance i have gotten of this plugin returning undefined in different parts of different libraries, but most of them were so difficult to reproduce i never bothered to report them. #104 is due to one of these undefined cases as well. In marko-widgets line 27 of `lib/registry.js` returns undefined.

**Comment by piuccio** [comment]
I'm having the same problem and I managed to create a tiny repo that shows the error.

https://github.com/piuccio/rollup-bug

@Rich-Harris it feels like rollup is now aggressively removing empty `if` statement, however it now removes the body of statements that are always true, while it should inline them.

**Comment by dev-nima** [comment]
I have the same issue when i switched to version 5

**Comment by Spy-Seth** [comment]
Same issue on my side. The upgrade to the v5 from the v3.3.1 allow my me to correctly import `react-intl` but generate this error.

**Comment by matrunchyk** [comment]
Same issue. I use rollup and react and it generates the error
![Alt text](https://monosnap.com/file/JgMtFsUGJMl5HmmKyxd0YWf5WPbY50.png)

**Comment by Rich-Harris** [comment]
Thanks for the repro, apologies for the delayed response – it looks like whatever odd bug was causing this was a bug in Rollup itself that was merely exposed by the change in behaviour between 4 and 5, rather than being a bug in this plugin. Updating Rollup to 0.37 should fix the issue, so I'll close this – shout if you still experience problems.
