### ISSUE TITLE
Des.js breaks due to a circular require

### ISSUE THREAD

**Issue by dignifiedquire** [rollup/rollup-plugin-commonjs#119]
(Sorry if this is the wrong repo, was unsure where to report)

When using `crypto`, which is shimmed through `browserify-crypto`, [des.js](https://github.com/indutny/des.js) which is used as a dependency of this will not be properly resolved. It looks like this is due to the cycle here:
- https://github.com/indutny/des.js/blob/master/lib/des/des.js#L6-L8 and 
- https://github.com/indutny/des.js/blob/master/lib/des/ede.js#L6-L8

The result I'm getting is

``` js
var assert$5 = index$55;
var inherits$20 = inherits_browser;

var des$4 = des$1;
var Cipher$6 = des$4.Cipher;
var DES$3 = des$4.DES;
```

where `des$1` is never actually defined.

**Comment by dignifiedquire** [comment]
Ref https://github.com/indutny/des.js/issues/2

**Comment by dignifiedquire** [comment]
Seeing the same pattern breaking in https://github.com/indutny/hash.js/blob/master/lib/hash/common.js#L1

**Comment by dignifiedquire** [comment]
Looks like this is an issue with named exports, plus known issue, as mentioned in https://github.com/calvinmetcalf/rollup-plugin-node-builtins/issues/3

**Comment by sebastien-de-saint-florent** [comment]
I have exactly the same issue on my project. According to the readme of builtins plugin : 
> some like crypto, are complex enough that they don't work very well with rollup at all

So I'm not sure this bug can be solved at the moment.

**Comment by Rich-Harris** [comment]
Sorry for the slow response. Based on @indutny's response on https://github.com/indutny/des.js/issues/2 a PR for that and https://github.com/indutny/hash.js/blob/master/lib/hash/common.js#L1 might be the quickest route to a resolution. Failing that would you be able to provide a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)? Thanks

**Comment by dignifiedquire** [comment]
In theory yes, but while doing the investigation I found out that quite a number of indutnys repos have the exact same structure (bn.js, and some others) which are all part of the crypto shims for the browser. So I am not sure if it makes sense to to PR all of those, or if it might be better to resolve the underlying issue here.

**Comment by Rich-Harris** [comment]
I'd like to resolve the issue here if it's possible, but it may not be – ES modules don't reflect CommonJS semantics in all cases. If you're able to generate a repro I'll have a better idea of that.

**Comment by swansontec** [comment]
I have made a test case here: https://github.com/swansontec/rollup-commonjs-circular-error-demo

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
