### ISSUE TITLE
Error transforming with 'commonjs' plugin: Octal literal in strict mode

### ISSUE THREAD

**Issue by thisconnect** [rollup/rollup-plugin-commonjs#122]
Hi I get this error

SyntaxError: Error transforming .../node_modules/jspm/lib/ui.js with 'commonjs' plugin: Octal literal in strict mode (467:28) in ..../node_modules/jspm/lib/ui.js

I suppose jspm it is coming from some postcss dependency. I try to bundle our build scripts to see if startup could improve. loading without executing the build script is ~1.5s I suppose due to tons of dependecies. (inspired by https://medium.com/@Rich_Harris/how-to-not-break-the-internet-with-this-one-weird-trick-e3e2d57fee28#.23ffihscu)

Not sure if this is important to the rollup project. Let me know if I should setup a repo

**Comment by Victorystick** [comment]
Octal literals are forbidden in strict mode, and since ES6 modules are implicitly strict... octal literals are not allowed as input to Rollup. It's out of scope for the CommonJS plugin to transform octal literals so that code using them can run. You could use some other plugin for that purpose.
