### ISSUE TITLE
IIFE parsing bug

### ISSUE THREAD

**Issue by ntilwalli** [rollup/rollup-plugin-commonjs#123]
The parser does not parse all IIFEs correctly.

```
(function () { return 'blah'; }()) // invalid?????
(function () { return 'blah'; })() // valid
```

Notice how the function-call parens immediately follow the closing brace and the whole expression is contained in outer parens...  Both styles are valid in Chrome and Node.

I am erroring out when trying to bundle `es5-ext` which uses the first style in multiple places like here: https://github.com/medikoo/es5-ext/blob/master/object/set-prototype-of/shim.js#L51

This style is also used in `es6-map` here:  https://github.com/medikoo/es6-map/blob/master/is-native-implemented.js#L9

**Comment by ntilwalli** [comment]
I've discovered this issue happens in the `Module.js` file of rollup itself, here: https://github.com/rollup/rollup/blob/cfbf78795e1d5454425635de94369b998c8f46b7/src/Module.js#L16

Closing in this repo.

**Comment by Rich-Harris** [comment]
closing via #124
