### ISSUE TITLE
Export named delete breaks

### ISSUE THREAD

**Issue by LinusU** [rollup/rollup-plugin-commonjs#130]
See https://github.com/sindresorhus/dot-prop/issues/32

When having an export named `delete` this module will cause the following error to be thrown by rollup:

> Error parsing node_modules/dot-prop/index.js: Unexpected token (78:4) in node_modules/dot-prop/index.js

Maybe automatically renaming `delete` to `_delete`, or having a config option where one can specify a new name...

**Comment by Rich-Harris** [comment]
This is the same as #116 and is fixed in 6.0.0. Let us know if you still have problems, thanks
