### ISSUE TITLE
`import * as` syntax not working

### ISSUE THREAD

**Issue by alan-agius4** [rollup/rollup-plugin-commonjs#136]
I am depending on various libraries which are not ES6, And I am importing most of them like the below

``` ts
import * as moment from 'moment';
import * as _ from 'lodash';
```

Reason being is that I want to ship my lib to ES6 and UMD. That said, it would be almost impossible to make it work with rollup. Since when I do so I will get errors that `_ is undefined`.

If I change the imports to;

``` ts
import lodash from 'lodash';
```

My UMD package won't be valid any longer as lodash doesn't have defaults.

Note, this is just an example and I have a handful of other libraries that I am using with the same issue.

It would be nice that `import * as` syntax is supported.

`Fusejs`, `Moment`, `Lodash` etc all have the same issue.

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff). Also, I recommend using `lodash-es` rather than `lodash`.

**Comment by Zhuoqing** [comment]
maybe related https://github.com/rollup/rollup-plugin-commonjs/issues/157

**Comment by Rich-Harris** [comment]
No repro, closing
