### ISSUE TITLE
'Greeter' is not exported by app\ts\greeter.js

### ISSUE THREAD

**Issue by kudorgyozo** [rollup/rollup-plugin-commonjs#138]
'Greeter' is not exported by app\ts\greeter.js (imported by app\ts\index.ts). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

```
export class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}
```

`import { Greeter } from './greeter';`

days wasted on rollup: **too many**

**Comment by thisconnect** [comment]
I am not sure about `.ts` stuff, but `import { Greeter } from './greeter.js';` should import your class, see [example](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwR3JlZXRlciUyMCU3RCUyMGZyb20lMjAnLiUyRkdyZWV0ZXIuanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMEdyZWV0ZXIlMjApJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMkdyZWV0ZXIuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwY2xhc3MlMjBHcmVldGVyJTIwJTdCJTVDbiUyMCUyMCUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy5ncmVldGluZyUyMCUzRCUyMCdIZWxsbyclM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUyMCUyMGdyZWV0KHBlcnNvbiklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwdGhpcy5ncmVldGluZyUyMCUyQiUyMCU1QyUyMiUyQyUyMCU1QyUyMiUyMCUyQiUyMHBlcnNvbiUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTdEJTIyJTdEJTVEJTdE)

**Comment by Rich-Harris** [comment]
@kudorgyozo Protip 1: 

> days wasted on rollup: too many

...is not a good way to ask for help.

Protip 2, [include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff).

**Comment by Rich-Harris** [comment]
No repro, closing
