### ISSUE TITLE
Plugin ignoring exclusions

### ISSUE THREAD

**Issue by Samlilli** [rollup/rollup-plugin-commonjs#140]
When using this plugin, it errors on transforming one of my node modules. The error is:

```
{ [SyntaxError: Error transforming /Users/sam/Desktop/sjl-portfolio-site/node_modules/beeper/index.js with 'commonjs' plugin: 'return' outside of function (9:1) in /Users/sam/Desktop/sjl-portfolio-site/node_modules/beeper/index.js]
  pos: 195,
  loc: Position { line: 9, column: 1 },
  raisedAt: 201,
  rollupTransform: true,
  id: '/Users/sam/Desktop/sjl-portfolio-site/node_modules/beeper/index.js',
  plugin: 'commonjs' }
```

So I try and exclude it explicitly by doing
```
commonjs({ include: './node_modules/**', exclude: './node_modules/beeper' }),
```

But I still get the same error. The result is that in the browser, I get the error
```
uncaught referenceError: require is not defined
```

Presumably because the plug in fails and isn't catching the 'requires'

Anyone know what the problem could be?

Thanks

**Comment by thisconnect** [comment]
Seems they fixed it https://github.com/sindresorhus/beeper/commit/e28f5f4e5ae916a2fd1bc2a170c25fe99746dcff
but not published

however beeper is for terminal beep, I doubt this will ever work in the browser.

**Comment by Samlilli** [comment]
@thisconnect Cheers for finding that - I removed the line of code manually and it appears to not break the build. 

However, I'm still getting the error 'require is not defined' in the browser, so I'm not sure it's importing nested dependencies properly?

**Comment by Rich-Harris** [comment]
It [works for me](https://gist.github.com/Rich-Harris/39128d7fecbc4e62c16f9b692ac52541), can you [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff) please?

**Comment by Samlilli** [comment]
This can be closed.. Apologies, can't remember what I did now but not a problem with this plugin. I asked the beeper owner to publish to npm so that fix is in there now.
