### ISSUE TITLE
Code's  structure changed after converted

### ISSUE THREAD

**Issue by seajean** [rollup/rollup-plugin-commonjs#143]
I have a  cjs module, and import in rollup project, however after converted, I found my code can not run  anymore, after I check the code, I found my code's structure has totally change,
it change into some code like these:

```javascript
var unWrapModule = unwrapExports(nativeModule);
var finallyObj = Object.freeze({
	default: unWrapModule,
	__moduleExports: nativeModule
});
````
and the finallyObj runs with many errors, cause  nativeModule's functions can not be accessed.
and Object freeze is not what I expected.

**Comment by Rich-Harris** [comment]
https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

**Comment by Rich-Harris** [comment]
No repro, closing
