### ISSUE TITLE
the `global`

### ISSUE THREAD

**Issue by lc60005457** [rollup/rollup-plugin-commonjs#15]
If it use `global` in my code, it will be transform with `commenjs`.

But, I use `import` and `export` of es2015 with rollup.

The rollup error:

```
[SyntaxError: 'import' and 'export' may only appear at the top level
```

**Comment by Victorystick** [comment]
@lc60005457 Thanks for reporting this issue. We're evaluating whether to drop the wrappers entirely #14 . That should solve this issue.
