### ISSUE TITLE
Unable to access the exports of 3rd-party module

### ISSUE THREAD

**Issue by brekk** [rollup/rollup-plugin-commonjs#154]
Hi there,

Apologies if this isn't in the right location. I've been trying to use rollup in conjunction with a couple commonjs modules. In general things seem to be working, but one file in particular seems to resist all attempts to roll it up.

I keep getting this error:
```
Error: Module ~/servers/work/frontend2/node_modules/sanctuary-def/index.js does not export default
```

From [sanctuary-def](https://github.com/sanctuary-js/sanctuary-def/blob/master/index.js#L150-L158), this peculiar structure seems to be causing a lot of grief:

```js
(function (f) {
  if (typeof module === 'object' && typeof module.exports === 'object') {
    module.exports = f()
  } else if (typeof define === 'function' && define.amd != null) {
    define([], f)
  } else {
    self.sanctuaryDef = f()
  }
})(function () {
  const someObject = {someProp: 'whatever'}
  return someObject
})
```

I've tried using namedExports in my [config file](https://gist.github.com/brekk/8afa95ac61c4bdf7933ecb5937b0632d) as well, though to no avail.

Is there some obvious thing I'm missing or doing wrong? I'm guessing that the `module.exports` nested inside of the IIFE is making things extra-complicated &mdash; is my best bet to re-write that module so that it has `module.exports` outside the IIFE?

Please let me know if there's additional detail I can provide.

Thanks for your time,

Brekk

**Comment by Rich-Harris** [comment]
I think this is another case of https://github.com/rollup/rollup/issues/1148 – can you try putting the node-globals and node-builtins plugins after the commonjs plugin and see if that fixes it? Thanks

**Comment by brekk** [comment]
@Rich-Harris Thanks, I tried that re-ordering, but still no luck. Using these plugins in this order, for reference (I tried a couple different orders while reading through the other issues, nothing seemed to obviously affect behavior):
```js
plugins: [
  progress(),
  json(),
  resolve({
    jsnext: true,
    module: true,
    main: true
  }),
  sass({
    // output: "build/rollup-bundle.css"
    output: false
  }),
  jsx({factory: "React.createElement"}),
  commonjs({
    sourceMap: false,
    include: "node_modules/**",
    extensions: [".js"]
    // namedExports: {
    //   ["node_modules/sanctuary-def/index.js"]: [
    //     "_$"
    //   ]
    // }
  }),
  globals(),
  builtins(),
  babel({
    exclude: "node_modules/**"
  })
],
```

**Comment by DanielJoyce** [comment]
Stuck here as well. I have noderesolve before the commonjs plugin, but I can't get the namedExports field to work. Its just ignored.

`'random' is not exported by 'node_modules/faker/index.js'`

``` javascript

import rollup from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs';
import uglify from 'rollup-plugin-uglify'

export default {
  entry: 'src/client/app/boot-aot.js',
  dest: 'dist/build.js', // output a single application bundle
  sourceMap: true,
  sourceMapFile: 'dist/aot/build.js.map',
  format: 'iife',
  // external: ["faker"],
  onwarn: function (warning) {
    // Suppress this error message... there are hundreds of them. Angular team says to ignore it.
    // https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined
    if (warning.code === 'THIS_IS_UNDEFINED')
      return;
    console.error(warning.message);
  },
  paths: (id) => {
    console.error("PATHS", id);
    return id;
  },
  plugins: [
    nodeResolve({
      jsnext: true,
      module: true,
      main: true
    }),
    commonjs({
      include: ['node_modules/rxjs/**'],
      namedExports: {
        // DOESNT WORK VVV
        'node_modules/faker/index.js': ['random','fake'],
      }
    }),
    uglify()
  ]
}
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
