### ISSUE TITLE
how to use import * as Clipboard from 'clipboard'

### ISSUE THREAD

**Issue by Zhuoqing** [rollup/rollup-plugin-commonjs#157]
repro repo is at https://github.com/Zhuoqing/rollupClipboard

The typings for [@types/clipboard@1.5.31](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d78b6c3b18025e63a71cdf57be00230f6ff72aa/clipboard/index.d.ts) is something like

    declare class Clipboard {...
    }
    
    declare namespace Clipboard {...
    }
    
    export = Clipboard;
    export as namespace Clipboard;

and its [usage example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d78b6c3b18025e63a71cdf57be00230f6ff72aa/clipboard/clipboard-tests.ts) is like 

    import * as Clipboard from 'clipboard';
    var cb1 = new Clipboard('.btn');
However when we try to bundle with rollup with same syntax, somehow `new Clipboard` doesn't work and we had to do `new Clipboard.default` which doesn't seem right.
#to repro
`npm i && npm run build`, then load `index.html` and watch the error in console, can also check [jsfiddle here](https://jsfiddle.net/93h4Lx3r/2/)

Note if change to use `import Clipboard from 'clipboard';` it works. However in our repo ngc/tsc will complain `module has no default export`, not sure what magic rollup-plugin-typescript is doing there. Also  looks like `import Clipboard = require('clipboard');` doesn't work because of es2015 module.

**Comment by Zhuoqing** [comment]
related to #143 
actual in generated bundle file 
```
var clipboard$1 = unwrapExports(clipboard);
var Clipboard = Object.freeze({
	default: clipboard$1,
	__moduleExports: clipboard
});
```
while we want it to be 
`var Clipboard = unwrapExports(clipboard);
`

**Comment by Hikariii** [comment]
We have a related issue like https://github.com/rollup/rollup/issues/1267

In Typescript we need to use this import:
```import * as $ from 'jquery';```

For rollup, the import has to be
```import $ from 'jquery';```

It looks like there is no way to solve this.
Writing ```import $ = require('jquery')``` compiles correctly from typescript for `commonjs`, but fails when compiling to `es2015`.

**Comment by DanielJoyce** [comment]
Same here, same problem.

**Comment by Rich-Harris** [comment]
Gah, this is what people get for messing around with TypeScript I'm afraid. This...

```js
import * as foo from 'whatever';
foo();
```

...just completely ignores how ES modules work — a namespace is a collection of exports, not a thing that can be called. If you can use `Clipboard.default` then I would do that, however wrong it feels — we can't account for TypeScript's quirks without breaking other stuff, so I'm afraid this is probably a wontfix.
