### ISSUE TITLE
namedExports detection for Rollup bundles

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-commonjs#159]
Infuriatingly, libraries that use Rollup to generate a UMD bundle don't have their named exports detected by this plugin. Notwithstanding the fact that those libraries should expose an ES module, we could probably detect this pattern:

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
  typeof define === 'function' && define.amd ? define(['exports'], factory) :
  (factory((global.lib = global.lib || {})));
}(this, (function (exports) {

exports.foo = 42;

Object.defineProperty(exports, '__esModule', { value: true });

})));
```

**Comment by kzc** [comment]
related issue: https://github.com/rollup/rollup/issues/1220#issuecomment-270499527

Modules like `ramda` written in this form:
```js
module.exports = {
  F: require('./src/F'),
  T: require('./src/T'),
  __: require('./src/__'),
  add: require('./src/add'),
  addIndex: require('./src/addIndex'),
  adjust: require('./src/adjust'),
...
```
Not only are the named exports not detected by rollup, unused symbols are not removed.

**Comment by iammerrick** [comment]
What is the workaround? namedExports option doesn't seem to be working? 
![screen shot 2017-02-21 at 9 44 26 pm](https://cloud.githubusercontent.com/assets/109635/23197641/f77c96ae-f87e-11e6-8eff-3f7e6e14c364.png)

**Comment by Rich-Harris** [comment]
Can you try changing `namedExports` to look like this?

```js
namedExports: {
  'node_modules/babylon/lib/index.js': [ 'parse' ]
}
```

**Comment by kushan85** [comment]
Even I can't get it working. I tried various options already

`rollup failed: 'Chart' is not exported by node_modules/chart.js/src/chart.js (imported by
            src/pages/home/home.ts). For help fixing this error see
            https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

`commonjs({
        namedExports: {
            // left-hand side can be an absolute path, a path
            // relative to the current directory, or the name
            // of a module in node_modules
            'node_modules/chart.js/src/chart.js': [ 'Chart' ]
        }
    })`

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
