### ISSUE TITLE
Consuming module with default is incorrect

### ISSUE THREAD

**Issue by unional** [rollup/rollup-plugin-commonjs#160]
`rollup-plugin-commonjs`: 7.0.0
`rollup`: 0.41.1

I have a module that does both default and named export (but I think a simple default export only module would demo the same issue) `global-store`.
It is bundled using `rollup`. 
I then consume it in another module, `color-map-rainbow`, and use `rollup` to bundle it too.

When loaded on the browser, the error is `global_store_1.default is not a function`.
Here is the bundled code: https://github.com/unional/color-map-rainbow/blob/rollup-default-erase/demo/color-map-rainbow.js

The shape of the `global-store` object is like this:

```js
GlobalStore = {
  default: function() { ...}
  getStore: function() { ... }
}
```

The issue is these two lines:
```js
...
globalStore = 'default' in globalStore ? globalStore['default'] : globalStore;
...
var global_store_1 = globalStore;
var store = global_store_1.default('color-map-rainbow', {});
```

https://github.com/unional/color-map-rainbow/blob/rollup-default-erase/demo/color-map-rainbow.js#L5
https://github.com/unional/color-map-rainbow/blob/rollup-default-erase/demo/color-map-rainbow.js#L43

It first replaces `globalStore` with `GlobalStore.default` (thus become a function), then accesses `global_store_1.default`, thus undefined.

**Comment by unional** [comment]
You can clone and get that branch to try it out:

```sh
git checkout rollup-default-erase
npm install
npm run build

# or 'start' for windows
open demo.html

**Comment by cmawhorter** [comment]
I can't get your repo to work but I think this might be related to rollup/rollup#600.  I'm having a similar problem with Joi.

The compiled output is:

```js
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
var joi = _interopDefault(require('joi'));
```

Since Joi module.exports something like `module.exports { default: }`, commonjs (?) incorrectly wraps it in interopdefault.

In your case, this likely means that instead of `global_store_1` being a reference to you object with `default` and `getStore`, it becomes a reference to `GlobalStore.default` itself.  Since `GlobalStore.default.default` is undefined it throws the error.

There might be some reason it's not, but _interopDefault should be rewritten as:

```js
function _interopDefault (ex) { 
  if (typeof ex === 'object') {
    var props = Object.keys(ex);
    if (props.length === 1 && props[0] === 'default') {
      return ex['default'];
    }
    else {
       return ex;
    }
  }
  else {
    return ex;
  }
}
```

That fixes the problem for me.

Alternatively, you can manually patch the bundled js and unwrap the require call:

```js
var some_dep = _interopDefault(require('some-dep'));
```

Becomes:

```js
var some_dep = require('some-dep');
```

**Comment by Rich-Harris** [comment]
Is it necessary for `GlobalStore` to have a `default` property that *isn't* the product of transpilation? (I see you're the maintainer of that project.) There's basically no way to solve this problem without breaking interop with modules that were e.g. generated by Babel, so I'm afraid this is probably a wontfix.

**Comment by unional** [comment]
Yes, the issue is more general. It fall back to the differences between the interop policies between ES2015 Modules and CommonJS among TypeScript and Babel/rollup (as you can see I wrote it in TS and transpile to ES5).

I've warned about this issue close to a year ago, and the problem begins to surface.

We need to have a solution to bring the TS and Babel/rollup community together.

**Comment by Rich-Harris** [comment]
I would strongly argue that the issue needs fixing on the TypeScript end. I'm not sure there's anything we can do as long as TypeScript compiles stuff in an idiosyncratic way, so I'll close this issue. To be honest you're probably better off using the TypeScript tooling rather than using Rollup.
