### ISSUE TITLE
Understand/Process TypeScript export statements

### ISSUE THREAD

**Issue by brian428** [rollup/rollup-plugin-commonjs#163]
I'm trying out the commonjs rollup plugin in an Angular 2 project. Everything seems OK until it tries to resolve exports for an external library (PrimeNG in this case).

The exports in primeng.js (which is compiled via TypeScript) look like this:

```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require('./components/common/api'));
__export(require('./components/common/shared'));
...etc...
```

The only way I can get things to work is to specify namedExports for this library. Unfortunately, there are roughly **70** exports that need to be declared.

Obviously, this is a huge pain, not only to create the list but to maintain it into the future. Could the plugin be made to understand these sorts of dynamic exports?

**Comment by Rich-Harris** [comment]
Afraid I can't see any way this could be done with static analysis, so unless anyone has any smart ideas this is a wontfix. To be honest it's not something that belongs in this project anyway — perhaps it could be done in a separate plugin?
