### ISSUE TITLE
Illegal reassignment to import 'commonjsHelpers'

### ISSUE THREAD

**Issue by chief10** [rollup/rollup-plugin-commonjs#166]
Running into this problem while trying to use this plugin. 

```
Illegal reassignment to import 'commonjsHelpers'
Error: Illegal reassignment to import 'commonjsHelpers'
    at error (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/utils/error.js:2:14)
    at disallowIllegalReassignment (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/nodes/shared/disallowIllegalReassignment.js:9:4)
    at AssignmentExpression.bind (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/nodes/AssignmentExpression.js:12:3)
    at /Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:6:34
    at ExpressionStatement.eachChild (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:21:5)
    at ExpressionStatement.bind (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:6:8)
    at /Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:6:34
    at IfStatement.eachChild (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:21:5)
    at IfStatement.bind (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/ast/Node.js:6:8)
    at Module.bindReferences (/Users/mike/Desktop/ClickTripz/trunk/integrations/node_modules/rollup/src/Module.js:262:9)
```

It looks like the error is coming from `/rollup-plugin-commonjs/src/transform.js`.

Here is my rollup.config.js:

```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import ruJson from 'rollup-plugin-json';
import ruSass from 'rollup-plugin-sass';
import ruRiot from 'rollup-plugin-riot';
import ruBabel from 'rollup-plugin-babel';
import ruBuble from 'rollup-plugin-buble';

export default {
  entry: 'work/specific/file.js',
  dest: './rollup.bundle.js',
  format: 'iife',
  plugins: [
    // ruBuble(),
    nodeResolve({ jsNext: true, main: true }),
    commonjs({
      extensions: [".js"]
    }),
    ruJson(),
    ruSass(),
    ruRiot()
  ]
}
```

**Comment by Rich-Harris** [comment]
[Please include a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

**Comment by stalkerg** [comment]
I have this problem too.

**Comment by stalkerg** [comment]
You can try just import this https://github.com/vigetlabs/gangway .

**Comment by jchook** [comment]
Here is a repro for this issue:
https://github.com/jchook/rollup-plugin-commonjs-166

I am getting the problem when trying to import [formidable](https://www.npmjs.com/package/formidable).

**Comment by jchook** [comment]
The common thread here seems to be the [use](https://github.com/felixge/node-formidable/blob/master/lib/incoming_form.js#L1) of [`global`](https://github.com/vigetlabs/gangway/blob/65976995a20ecc2fd7102a429718146340183d2f/src/prepare.js#L23).

I would be willing to bet this is due to a commonjs 'runtime' namespace collision with the library being compiled.

**Comment by jchook** [comment]
@Rich-Harris this issue now has a repro and a diagnosis.

**Comment by bfred-it** [comment]
For reference, it works in browserify:

```sh
echo "require('formidable')" | browserify -
```

And this is the clearer error shown in more recent rollup versions:

```
🚨   Illegal reassignment to import 'commonjsHelpers'
node_modules/formidable/lib/incoming_form.js (29:43)
27: import os from 'commonjs-proxy:os';
28: 
29: if (commonjsHelpers.commonjsGlobal.GENTLY) commonjsHelpers.commonjsRequire = GENTLY.hijack(commonjsHelpers.commonjsRequire);
                                               ^
```

This is a bit of an edge case. Rollup tries to be smart about `require` and reassigning it is pulling the rug from under its feet.

**Comment by bruce-one** [comment]
Another possible solution is to use [unlazy-loader](https://github.com/doowb/unlazy-loader) to leverage the fix/workaround done for Webpack, eg

```
import unlazyLoader from 'unlazy-loader'
import { createFilter } from 'rollup-pluginutils'

export default function unlazy ( options = {} ) {
    const filter = createFilter( options.include, options.exclude )

    return {
        name: 'unlazy'

        , transform ( source, id ) {
            if ( !filter( id ) ) return null
            var res = unlazyLoader(source)
            if(res === source) return
            return res
        }
    }
}
```

(Might be dodgy etc, but seemed to work well enough for us at this point :-) )

**Comment by antony** [comment]
In case it helps, another case where this happens is ethereum's web3 js library.

https://github.com/ethereum/web3.js/blob/develop/dist/web3.js

**Comment by ronanquillevere** [comment]
Same problem for me with superagent and formidable, thanks for the hack @jchook !

**Comment by luisrudge** [comment]
I'm still having this issue with any library that imports superagent. none of the replace workarounds fixed it for me :(

**Comment by benjamingr** [comment]
@luisrudge thanks! your fix worked for me and it's a lot less hacky than the alternatives of rewriting the file contents with regex <3

**Comment by colllin** [comment]
Still a problem these days 🙄.  I found this solution in an issue about webpack somewhere:

    replace({
        'global.GENTLY': false,
    })

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by CodeTroopers** [comment]
@shellscape I have the same issue with [to-file module](https://www.npmjs.com/package/to-file) where the author (@jonschlinkert) reassign require [here](https://github.com/jonschlinkert/to-file/blob/47bc0f9798181fe54e29451da80fbcb2dff97917/utils.js#L12)
Must i open a new issue in the new repository? Must i open issue in `to-file` module ?
