### ISSUE TITLE
namedExports is using non-normalized resolved module path as module id

### ISSUE THREAD

**Issue by ezolenko** [rollup/rollup-plugin-commonjs#177]
On windows, this can conflict with plugins using other resolvers. For example typescript's built-in resolver returns module paths using forward slashes, while commonjs takes output of `resolve` at face value. Since that happens to return system native path with backslashes (in ver 1.1.7 at least), mishaps can result depending on which plugin happened to resolve a given module first. 

One way to fix it would be to normalize path before using it as a key.

**Comment by Rich-Harris** [comment]
Thanks. This sounds like the sort of thing I'm liable to mess up if I try and fix it — any chance you could put a simple repro together that could be turned into a test case (or better yet, a PR with said test, or even a fix)?

**Comment by ezolenko** [comment]
Reproducing it is the main problem, yeah. I only saw it on somebody else codebase...
