### ISSUE TITLE
Can't import named exports - (Affecting react, react-dom among others)

### ISSUE THREAD

**Issue by ajaska** [rollup/rollup-plugin-commonjs#185]
Hi, I'm getting problems on `rollup` 0.41.6 + `rollup-plugin-commonjs` 8.0.2 with importing named exports from react, react-dom, react-dates.

I'm pretty sure this worked before, so I made this minimal example which causes issues (and as far as I am able to tell, `rollup-plugin-commonjs` should be able to handle). It works fine just babelifying it.

I'm invoking `rollup -c`, here is `rollup.config.js`:

```javascript
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

const options = {
  entry: 'index.js',
  dest: 'output.js',
  format: 'umd',
  plugins: [
    nodeResolve(),
    commonjs(),
  ],
};

export default options;
```

Here's my `index.js`
```javascript
import { MyFunction } from 'fake-repro-package';

console.log(MyFunction());
```

And here's `node_modules/fake-repro-package/index.js`:
```javascript
module.exports = {
  MyFunction: function() { return 8; },
};
```

This results in the error:
```javascript
🚨   'MyFunction' is not exported by node_modules/fake-repro-package/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
index.js (1:9)
1: import { MyFunction } from 'fake-repro-package';
            ^
2: 
3: console.log(MyFunction());
```

**Comment by ajaska** [comment]
FWIW, adding them to the named exports does appear to work -- but I don't think I should have to be doing that for such a trivial case (which the docs say should work :) ).

**Comment by ajaska** [comment]
I did a quick check, and with `rollup@0.41.6`,

Versions of `rollup-plugin-commonjs` through 4.1.0 work with this example, versions 5.0.0+ require the namedExports workaround. A quick visual inspection suggests #186 may be related, and #115 looks very much related -- even noting the fix of downgrading to 4.1.0

**Comment by ajaska** [comment]
Ah, I hate to be intrusive and tag you directly, I'm sure you're quite busy, but @Rich-Harris any chance you could take a look at this?

This is a clear regression (with repro!) and I'm not going crazy, right?

**Comment by flying-sheep** [comment]
i encountered this as well: https://github.com/flying-sheep/rollup-typescript-test/tree/implicit-exports

**Comment by kirbdee** [comment]
You need to explicitly name "MyFunction" in the namedExports config.

Another alternative (which is interestingly observed and I'm not sure if this is intended):

```
import {default as fakeRepo} from 'fake-repo-package';

fakeRepo.MyFunction() //this will be available w/o any nameExports
```

**Comment by ajaska** [comment]
Right, those are both workarounds, that should function (but adding tons of namedExports can get annoying fast).

It used to work without needing `namedExports`. I've switched back to webpack for now :)

**Comment by kopax** [comment]
I think I might have the same error with redux and redux-form, I've  posted here en [SO](https://stackoverflow.com/questions/46499188/rollupjs-es6-module-cant-get-imported-because-of-default-not-found-for-redux-an). Any workaround ?

**Comment by rtsao** [comment]
Experiencing the same issue with `enzyme-adapter-react-16` (as well as `react`, etc.)

**Comment by kopax** [comment]
I've managed to solved many case of named exports by using `modulesOnly: true`

**Comment by geoyws** [comment]
@kopax modulesOnly: true solved my problem. Thanks man.

**Comment by onlywei** [comment]
@kopax @geoyws what is "modulesOnly"? I don't see that as an option of this plugin.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
