### ISSUE TITLE
Code outside of createCommonjsModule throwing runtime error

### ISSUE THREAD

**Issue by treyrich** [rollup/rollup-plugin-commonjs#187]
I'm working on a project that is based on [mgechev/angular-seed](https://github.com/mgechev/angular-seed) and am having a very odd problem. When I use rollup to bundle my code, the resulting code throws an `Uncaught ReferenceError: exports is not defined` error in the browser.

Looking at the resulting code, it appears that code that should be contained in a call to `createCommonjsModule` is not.

Here's the top of the bundle from my project:
```
(function () {
'use strict';

var global$1$1 = typeof global !== "undefined" ? global :
            typeof self !== "undefined" ? self :
            typeof window !== "undefined" ? window : {};

/**
 * window: browser in DOM main thread
 * self: browser in WebWorker
 * global: Node.js/other
 */
exports.root = (typeof window == 'object' && window.window === window && window
    || typeof self == 'object' && self.self === self && self
    || typeof global$1$1 == 'object' && global$1$1.global === global$1$1 && global$1$1);
if (!exports.root) {
    throw new Error('RxJS could not find any global context (window, self, global)');
}


var root = Object.freeze({

});

var commonjsGlobal = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};





function createCommonjsModule(fn, module) {
	return module = { exports: {} }, fn(module, module.exports), module.exports;
}

function isFunction(x) {
    return typeof x === 'function';
}
var isFunction_2 = isFunction;
```
Compared to the top of the bundle from the seed project referenced earlier:
```
(function () {
'use strict';

var commonjsGlobal = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {};





function createCommonjsModule(fn, module) {
	return module = { exports: {} }, fn(module, module.exports), module.exports;
}

var root = createCommonjsModule(function (module, exports) {
"use strict";
/**
 * window: browser in DOM main thread
 * self: browser in WebWorker
 * global: Node.js/other
 */
exports.root = (typeof window == 'object' && window.window === window && window
    || typeof self == 'object' && self.self === self && self
    || typeof commonjsGlobal == 'object' && commonjsGlobal.global === commonjsGlobal && commonjsGlobal);
if (!exports.root) {
    throw new Error('RxJS could not find any global context (window, self, global)');
}

});

function isFunction(x) {
    return typeof x === 'function';
}
var isFunction_2 = isFunction;
```

It's not immediately clear what would cause such a thing to happen, the only major differences between the two projects are the dependencies, but what's confusing me is that the code referenced is VERY similar, but one seems to have output correctly, where the other seems almost random in the way it was output.

Forgive me if this isn't an issue with rollup/rollup-plugin-commonjs but it seems as though it's the most likely candidate.

**Comment by treyrich** [comment]
Looks like I may have found the culprit. It appears that this is a result of using `rollup-plugin-node-builtins` and `rollup-plugin-node-globals`. When those two plugins are removed, this issue doesn't occur. I'm not sure whether that makes this a bug with one of those plugins, or this one, but clearly the interoperability between the plugins is lacking somehow.

**Comment by bfred-it** [comment]
Thanks. Any chance you can [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by treyrich** [comment]
Possibly, if I come across it again. Unfortunately I had a pretty time-sensitive need to get the project building, and I can't remember what combination of things I ended up doing to get things working. I believe that I just removed the need for the conflicting plugins.

I do still believe that this is a bug, but I can't think back to what hacky work around I made 2 months ago. Sorry.

If I get some time over the next little bit I'll try to dig into this and recreate, but truth be told it's not a huge priority for me at this point as we're working on migrating our build system to webpack.

**Comment by mgtsai** [comment]
This bug has not been resolved yet. Any conclusion?

**Comment by gewentao** [comment]
getting into the same issue, any conclusion here?

**Comment by adrianheine** [comment]
Can you provide a repository reproducing the issue?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
