### ISSUE TITLE
npm inherits use rollup-plugin-commonjs cause TypeError

### ISSUE THREAD

**Issue by JackieLin** [rollup/rollup-plugin-commonjs#189]
Hi:

My project use [inherits](https://www.npmjs.com/package/inherits) as a third library. My rollup config like this:

    'use strict';

    const rollup = require('rollup')
    const nodeResolve = require('rollup-plugin-node-resolve')
    const commonjs = require('rollup-plugin-commonjs')
    const nodeGlobals = require('rollup-plugin-node-globals')
    const builtins = require('rollup-plugin-node-builtins')

    rollup.rollup({
        entry: 'inherits.js',
        plugins: [
            nodeResolve({
                extensions: ['.js'],
                preferBuiltins: false
            }),
            commonjs(),
            nodeGlobals(),
            builtins()
        ],
    }).then(bundle => bundle.write({
        dest: 'bundle.js',
        format: 'iife',
        moduleName: 'eagle'
    })).catch(err => console.log(err.stack))

After that, I run `node ./rollup.config.js` to build, There are two problems:

* It introduce all nodejs util lib, I just want to run in browser, the file is too large
* It occurs an error: `Uncaught TypeError: Cannot read property 'inherits' of undefined`

How can I do?

**Comment by calvinmetcalf** [comment]
do `import {inherits} from 'util'`;

also change your order to nodeGlobals, builtins, nodeResolve, commonjs

**Comment by bfred-it** [comment]
> It introduce all nodejs util lib, I just want to run in browser, the file is too large

There's nothing that can be done about it. If it requires the libs they will be included (by `builtins`). You can either send a PR to the offending lib to remove the dependency, or use a separate lib.
