### ISSUE TITLE
"module is not defined" error if "exports" is defined

### ISSUE THREAD

**Issue by matthew-dean** [rollup/rollup-plugin-commonjs#191]
I posted this elsewhere, but I think this is a problem specific to this plugin, since removing it from Rollup cures the issue. It looks like this plugin globally globally injects `exports` but not `module` into the final bundle. A lot of bundles use code like this:

```js
(function(factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else if (typeof exports !== 'undefined') {
        module.exports = factory(require('jquery'));
    } else {
        factory(jQuery);
    }

}(function($) {
```

So, as you can see, it checks for the existence of `exports`, which Rollup (or this plugin) has defined. However, that immediately fails on the next line because `module` is not defined. AFAIK the two are supposed to go together. The plugin defines the following at the top of bundles:

```js
(function (exports) {
'use strict';
```

So many Rollup builds will fail for this reason. At least that's the reason I'm finding for this error for me.

**Comment by matthew-dean** [comment]
I'm not sure if this is related to: https://github.com/rollup/rollup/issues/892

**Comment by matthew-dean** [comment]
See related issue: http://stackoverflow.com/questions/33353406/getting-referenceerror-jquery-is-not-defined-for-package-install-on-npm

**Comment by calvinmetcalf** [comment]
I just tested and was unable to reproduce this on the most recent version of this plugin, module IS included if it's referenced as is exports, I tested very similar code to what you had and it worked, your error likely in the thing that is being wrapped in the UMD or you are using an old version of something.

```js
(function(factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else if (typeof exports !== 'undefined') {
        module.exports = factory(require('./foo'));
    } else {
        factory(jQuery);
    }

}(function(foo) {
  return {
    foo,
    bar: 19
  }
}))
```
