### ISSUE TITLE
How to treat empty file

### ISSUE THREAD

**Issue by otakustay** [rollup/rollup-plugin-commonjs#194]
Today I encountered an error using rollup and rollup-plugin-commonjs to bundle my lib:

```
'default' is not exported by 'node_modules/core-js/library/modules/es6.object.to-string.js'
```

After some research I find this issue comes from [core-js/library/modules/es6.object.to-string.js](https://github.com/zloirock/core-js/blob/master/library/modules/es6.object.to-string.js) being an emty file

I manually put a `module.exports = null` statement in this file then bundled my lib successfully, but I'm wondering if it can be handled by rollup-plugin-commonjs itself as an edge case

**Comment by jonataswalker** [comment]
I solved this with - [rollup-plugin-hypothetical](https://www.npmjs.com/package/rollup-plugin-hypothetical):

```javascript
  plugins: [
    hypothetical({
      allowRealFiles: true,
      files: {
        './node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.to-string.js': 'export default null'
      }
    })
```

**Comment by otakustay** [comment]
@jonataswalker Thanks for great hint, I'm also expecting rollup-plugin-commonjs can handle this properly since hypothetical plugin requires a fs path instead of a module name

**Comment by bfred-it** [comment]
Duplicate of https://github.com/rollup/rollup/issues/1408

It still works regardless of the warning, right?

**Comment by trusktr** [comment]
It does still work regardless of the warning. :)
