### ISSUE TITLE
'default' is not exported error when use react and react-dom

### ISSUE THREAD

**Issue by alwaysonlinetxm** [rollup/rollup-plugin-commonjs#201]
Hi,  I used rollup to bundle my code which use react, and encounted some problems.

At first, @olsonpm told me to put babel plugin before commonjs  in  https://github.com/rollup/rollup/issues/1415#issuecomment-304750331  and actually it worked, so I did it. And then, I found that  the global and buildin plugins must be placed before commonjs and after babel, or there will be "default' is not exported ..." error:

```JavaScript
yarn run v0.24.5
$ NODE_ENV=development rollup -c -w 
bundling...
⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/buffer-es6/index.js (1:131)
1: import * as index from "/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
                                                                                                                                      ^

⚠️   'default' is not exported by 'node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js (1:189)
1: import * as stringDecoder from "/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js"; export default ( stringDecoder && stringDecoder['default'] ) || stringDecoder;
```

 So my config became like this:

```JavaScript
{
  entry: 'index.js',
  dest: 'dist/bundle.js',
  format: 'cjs',
  plugins: [
    nodeResolve({
      preferBuiltins: true
    }), // for support external module in node_modules
    json(),
    babel({
      exclude: "node_modules/**",
    }), // before global and buildin to solve "'default' is not exported by xxx..."
    globals(), // to include Node globals
    nodeBuildin(), // to include Node builtins, some modules may depand on global
    commonjs(), // in the end to solve many problems
  ]
}
```

With this config, everything seemed to be OK, but problem comes when I imported react and react-dom in my code:

```JavaScript
yarn run v0.24.5
$ NODE_ENV=development rollup -c -w 
bundling...
⚠️   'default' is not exported by 'node_modules/buffer-es6/index.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/buffer-es6/index.js (1:131)
1: import * as index from "/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/buffer-es6/index.js"; export default ( index && index['default'] ) || index;
                                                                                                                                      ^

⚠️   'default' is not exported by 'node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js'
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js (1:189)
1: import * as stringDecoder from "/Users/alwaysonlinetxm/txm/rollup_issue/node_modules/rollup-plugin-node-builtins/src/es6/string-decoder.js"; export default ( stringDecoder && stringDecoder['default'] ) || stringDecoder;
                                                                                                                                                                                                ^
```

I have searched this problem in other issues, and found that many people have similar problems with me. But unfortunately, I didn't find a solution to solve my problem. With the experience before, I guess it's something to do with the order of plugins. So I tried to adjust, but failed to find out the right order. And I am confused now, becouse I saw https://github.com/rollup/rollup-plugin-commonjs/issues/137#issuecomment-267096734 and https://github.com/rollup/rollup/issues/1148, in which @Rich-Harris said that globals and builtins plugins need to go after commonjs, and commonjs plugin needs to run before the babel plugin. Really?? Why is this opposite with my experiments？And how could I solve my problem with react?

Here's the project to repuduce this issue: https://github.com/alwaysonlinetxm/rollup_issue.

**Comment by olsonpm** [comment]
What rollup version are you using?  I ask because:
1. I get the following output with `yarn run start`
```sh
yarn run v0.24.5
$ NODE_ENV=development rollup -c -w 
bundling...
bundled in 659ms. Watching for changes...
```

2. rollup isn't listed as a dependency in your project.  FYI best practice is to not rely on global CLI's and instead point to your project's `./node_modules/.bin/rollup` binary.

**Comment by alwaysonlinetxm** [comment]
@olsonpm Thanks first, my global rollup CLI version is 0.41.6, and I have installed rollup locally in my project, the version is 0.42.0. But it seemed I still got the same problem.

The issue project has been updated:  https://github.com/alwaysonlinetxm/rollup_issue.

**Comment by olsonpm** [comment]
I was able to reproduce this time.  Taking a look

**Comment by olsonpm** [comment]
Well I learned a bit.  In short:

 - Don't worry about these because they are invalid warnings caused by this plugin.  I have an [issue open](https://github.com/rollup/rollup/issues/1408) to address this, but I now realize we have the capability of removing this warning via the [onwarn](https://github.com/rollup/rollup/wiki/JavaScript-API#onwarn) config option.  The only issue is you can't [pass a warning to rollup's default warning handler](https://github.com/rollup/rollup/issues/408#issuecomment-271309679), so you're left to handle the correct warning formatting yourself.

The following is verbose but hopefully readable code to remove these invalid warnings and output all others.

<details><summary>working `onwarn` solution</summary>

```js
// rollup.config.js

// I placed this past imports but before `export default`
const getModuleRe = /.*\/(.*?)\.js'$/
  , warn = msg => console.warn(msg)
  ;

// ...

  onwarn(aWarning) {
    const { code, frame, loc, message, url } = aWarning
      , moduleName = getModuleName(message)
      ;

    if (
      code === 'MISSING_EXPORT'
      && startsWith('\u0000commonjs-proxy:', loc.file)
      && startsWith("'default' is not exported by", message)
      && notActuallyMissingDefaultExport(frame, moduleName)
    ) {
      // do nothing
      return
    } else {
      // just a quick, colorless version of rollup's default warning
      const lines = [message, url, `${loc.file} (${loc.line}:${loc.column})`, frame];
      lines.forEach(warn);
    }
  }
};

// ...

// I placed these after the `export default` section
function startsWith(startsWithThis, aString) {
  return aString.slice(0, startsWithThis.length) === startsWithThis;
}

function getModuleName(warningMessage) {
  return warningMessage.match(getModuleRe)[1];
}

function notActuallyMissingDefaultExport(frame, moduleName) {
  const safeDefaultExportRe = new RegExp(
    `export default ( ${moduleName} && ${moduleName}['default'] ) || ${moduleName};`
  );

  return safeDefaultExportRe.test(frame);
}
```

</details>

**Comment by alwaysonlinetxm** [comment]
@olsonpm I added your code in my config as onwarn, and updated my code to run in browser, finding that there's no warnings any more, but the code still can't run correctly. I got the following error in browser console, just as same as without your code:

```JavaScript
bundle.js:8 Uncaught ReferenceError: require is not defined
    at bundle.js:8
    at bundle.js:18413
```
Does this mean those warnings are not invalid?

And I found another strange thing, if I use your code without global and buildin plugins, the following error will throwed by rollup: 

```JavaScript
yarn run v0.24.5
$ NODE_ENV=development rollup -c -w 
⚠️   'default' is imported from external module 'rollup-plugin-node-builtins' but never used

⚠️   'default' is imported from external module 'rollup-plugin-node-globals' but never used

bundling...
🚨   Cannot read property '1' of null
```

my issue project has been updated to reproduce now.

**Comment by olsonpm** [comment]
@alwaysonlinetxm - your confusion is very valid.  Unfortunately I don't know of any hard-fast rules for the plugin order.  The only order that makes sense to me at the moment is:

```js
'node resolve' then 'commonjs' then ('builtins' and 'globals')
```

As for the order of babel and commonjs - it seems to me that depends on the code base and shouldn't always be `'babel' then 'commonjs'` or vice versa.

As for debugging this isssue yourself in the future, you need to start simple e.g.

```js
// index.js
`import 'isomorphic-fetch'`
```

```js
// rollup.config.js
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  entry: './index.js'
  , dest: './bundle.js'
  , format: 'iife'
  , plugins: [
    nodeResolve({ preferBuiltins: true })
  ]
};
```
and add more plugins one by one to see what causes the issue.  Doing this is how I found out that `globals` coming before `commonjs` was the issue.  I also knew that commonjs was having an issue because the browser error you were getting was tripping up on a `require` call (require doesn't exist in the browser).

**Comment by alwaysonlinetxm** [comment]
@olsonpm Thank you for your advise! Your solution really worked. Now I think the plugin order is one of the biggest problems for us to use rollup, hoping this problem can be solved in the near future.

**Comment by thomasgwatson** [comment]
Most of the above advice didn't work for me when trying to build React components with Rollup.

Instead this seems to be best option we got at the moment: just don't include problematic externals and list them as peerDependencies:

https://medium.com/tech-grandata-com/how-i-set-up-a-react-component-library-with-rollup-be6ccb700333
https://hackernoon.com/publishing-baller-react-modules-2b039d84bce7
https://github.com/transitive-bullshit/react-modern-library-boilerplate

**Comment by olsonpm** [comment]
if you put together a minimal example i'd be interested in taking a look.

Sent from ProtonMail mobile

-------- Original Message --------
