### ISSUE TITLE
Halp (if possible) please.

### ISSUE THREAD

**Issue by Loque-** [rollup/rollup-plugin-commonjs#203]
I'm trying to use this for the first time after getting the following error with fancybox;

```
'default' is not exported by node_modules/@fancyapps/fancybox/dist/jquery.fancybox.js (imported by path/to/filename.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
```

If I then go and add the config to rollups config object as per docs;

```
commonjs({
    sourceMap: false,
    namedExports: {
        'node_modules/@fancyapps/fancybox/dist/jquery.fancybox.min.js' : [ 'somename' ]
    },
}),
```

I then see this instead;

```
Could not resolve 'somename' from path/to/filename.js
```

I'm not sure what part of the documentation I am missing to get this working.

Thanks so much for your time!

**Comment by bterlson** [comment]
FWIW many years later, the namedExports key has the .min.js file but should probably be the module name like `@fancyapps/fancybox`.
