### ISSUE TITLE
Error transforming `debug`

### ISSUE THREAD

**Issue by Rich-Harris** [rollup/rollup-plugin-commonjs#204]
Haven't looked into this at all, just opening a corresponding issue to https://github.com/visionmedia/debug/issues/468

**Comment by StreetStrider** [comment]
Sometimes instead of:
```js
exports = module.exports = function Something () { … }

exports.is = function (smth) { … } /* «static» member */
```

I do:
```js
var Something = module.exports = function Something () { … }

Something.is = function (smth) { … }
```
for better readability.

**Comment by StreetStrider** [comment]
@Rich-Harris, hey, need help here? I can prepare a PR but it may take some time for me to dive into codebase.

For some reason my usual workaround for this obstacle didn't work well in `debug`'s case and I don't know why. Maybe it's time to solve that centralized in this plugin.

**Comment by AlexGhiondea** [comment]
Hi!

I am also running into issues with consuming debug in rollup, with this error:

```
3: import debugModule from "debug";
          ^
4: /**
5:  * @ignore
Error: 'default' is not exported by node_modules/debug/src/browser.js
```

I have tried configuring rollup to use a namedExport like so:

```javascript
        namedExports: {
          "node_modules/debug/src/browser.js": ["debug"]
        }
```

However, the error is still there.

Any suggestions on how to continue debugging this?

**Comment by kopax** [comment]
I have the same error, any idea?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by StreetStrider** [comment]
@shellscape this is definitely worth to check after moving into new repo. Some (popular) cjs modules may accidentally «not work» because of not straghtforward cjs exports. But Rich once said the heuristics to detect it is totally doable on Rollup side.

**Comment by shellscape** [comment]
@StreetStrider good to know. Should that be a concern for this plugin, or for Rollup core? (I can transfer this issue to the rollup core repo as well)

**Comment by StreetStrider** [comment]
@shellscape I think it's in rollup-plugin-commonjs responsibility, but I might be wrong.
visionmedia/debug#468 got a very detailed symphtoms on this. They fixed their usage of cjs, but it's a pretty common pattern for cjs exports.
