### ISSUE TITLE
"name-is-not-exported-by-module" for default export

### ISSUE THREAD

**Issue by gcharnock** [rollup/rollup-plugin-commonjs#206]
I'm attempting to use rollup for the first time, and I've encountered errors that look like "Error: 'foo' is not exported by node_modules/fast-json-patch/src/json-patch-duplex.js" a few times. The advice suggested by the error message has generally worked. 

https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

However, what do I do when the object I want is the default export from the module? I've tried:
```
namedExports: {
    "node_modules/fast-json-patch/src/json-patch-duplex.js": ["default"]
}
```

Though I wan't really expecting the above to work (what if the module exported a non-default property called "default"?) and it didn't. I'm not sure what to do.

I'm sorry if this turns out to be a stupid question. All the previous "modern" javascript I've done has been server side. I'm finding all the seemingly countless module systems extremely confusing.

**Comment by bfred-it** [comment]
This is a recurring issue. Take a look at the existing issues to hopefully find a solution.

**Comment by gcharnock** [comment]
So I was able to find this https://github.com/rollup/rollup-plugin-commonjs/issues/186, but the suggested answer doesn't work any more:

```
    Error: options.skip is no longer supported — you should use the main Rollup `externals` option instead
```

So I tried "external" in the main options

```
    external: ["fast-json-patch"],
```

This does compile, but fails at runtime.

```
require.js:168 Uncaught Error: Script error for "fast-json-patch", needed by: benchmark-standalone
````

(Note that I had a requirejs available on my page, otherwise I assume the error would be something like `require is not defined`). So I need to find a cdn version of fast-json-patch in AMD format.

**Comment by isiahmeadows** [comment]
I found [this particular issue](https://github.com/rollup/rollup/issues/1408), and it proposed [changing `mod['default']` to `mod['def' + 'ault']`](https://github.com/rollup/rollup/issues/1408#issuecomment-306384674) as a fix.

**Comment by awerlang** [comment]
Instead of `import myModule from 'my-module';` try using `import myModule from 'node_modules/my-module/dist/my-module.js'`.

**Comment by otolab** [comment]
I think `"def"+"ault"` is too hacky, so I tried write it in other ways, PR #243.

It checked whether exporting "default" by AST, switch commonjs-proxy code by with / without "default".

Maybe processing cost increase slightly but that way is better.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
