### ISSUE TITLE
Can produce IIFE modules that declare variables in module scope

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [rollup/rollup-plugin-commonjs#213]
Hi all,

I presume this is a bug, but am not certain. A feature of the `format: 'iife'` option, I expect, is that it won't have certain side effects such as assigning to properties of the global object. This doesn't appear to be the case.

I've prepared an [SSCCE](http://sscce.org/) in [this](https://github.com/spencerwilson-optimizely/rollup-plugin-commonjs-213) repo.

**Relevant details:**
```js
const lib = require('./lib');

console.log(`Computing... 1 + 2 = ${lib.add(1, 2)}`);
```

produces

```js
var example = (function () {
'use strict';

function add(augend, addend) {
  return augend + addend;
}


var lib = Object.freeze({
	add: add
});

var lib$1 = ( lib && undefined ) || lib;

console.log(`Computing... 1 + 2 = ${lib$1.add(1, 2)}`);

var main = {

};

return main;

}());
```

, whereas
```js
import * as lib from './lib';

console.log(`Computing... 1 + 2 = ${lib.add(1, 2)}`);
```

produces

```js
(function () {
'use strict';

function add(augend, addend) {
  return augend + addend;
}

console.log(`Computing... 1 + 2 = ${add(1, 2)}`);

}());
```

I expect the former to _not_ declare a variable in the module scope (which, in a browser, undesirably sets a property on `window`).

**Comment by bfred-it** [comment]
This does look like a bug on an undefined behavior: you're using `require` to import a ES Module. 

Apparently you can `import` a CJS module, but not viceversa. I wouldn't use `require` on an ES Module.

**Comment by spencerwilson-optimizely** [comment]
Ah, good point. It's worth noting that the same output is still given when importing a commonjs module:
```
diff --git a/src/lib.js b/src/lib.js
index e82877e..fdb83ed 100644
--- a/src/lib.js
+++ b/src/lib.js
@@ -1,3 +1,3 @@
-export function add(augend, addend) {
+exports.add = function (augend, addend) {
   return augend + addend;
 };
```
produces
```js
var example = (function () {
// ...
```

In that light--namely, `require`ing a commonjs module--the same bug is present. I think that's the principal use case for the plugin, if I'm not misunderstanding. (Our package is all commonjs modules right now; we have yet to refactor to native modules.)

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
