### ISSUE TITLE
Order issue: module declared after it's needed 

### ISSUE THREAD

**Issue by adjourn** [rollup/rollup-plugin-commonjs#215]
### Example:

```js
var useIt = index.foo || index; // both undefined

var index = createCommonjsModule(function (module, exports) {
  // ...
});
```

--- 

Im not sure if it's because of plugin or `redis` package. Can it be fixed w/o manual copy-pasta every time?

### How to replicate:
1. install `redis` npm package
2. use the following Rollup plugins:

```js
plugins: [
  json(),
  resolve({
    jsnext: true,
    module: true,
    main: true
  }),
  commonjs({
    sourceMap: false,
    include: 'node_modules/**',
    extensions: ['.js'],

    // Node.js core modules
    ignore: [
      'crypto', 'string_decoder', 'util', 'events', 'url', 
      'tty', 'fs', 'net', 'tls', 'stream', 'assert'
    ]
  }),
],
```

3. entry file:

```js
import {createClient} from 'redis';
// or
import redis from 'redis';
```

### How to manually fix:

Just copy-paste whole `var index = createCommonjsModule(/* ... */);` before it's needed.

**Comment by BehindTheMath** [comment]
I'm having the same issue.

As part of a bigger project, I'm using this plugin to convert the [xmlbuilder]() package to ES6 modules. Within the package, `XMLElement` requires `XMLNode` (see [here](https://github.com/oozcitak/xmlbuilder-js/blob/f1c99a9c2abec65238ce86e8ed48bf9cb162ac6c/src/XMLElement.coffee#L3)), but in the output, `XMLElement` is declared first, causing the dependency on `XMLNode` to return `undefined`, which in turn throws an error, crashing the whole bundle.

**Comment by Rich-Harris** [comment]
Large old CommonJS projects are rife with gnarly circular dependencies and other things that just don't translate well to ESM. `redis` is probably one such example. The workaround is fairly straightforward — don't bundle it:

```js
// rollup.config.js
export default {
  external: ['redis'],
  ...
};
```

As for the xmlbuilder case, you probably just need to change the order of some `require`/`import` statements somewhere. The hard part is knowing which ones! (It is often very counterintuitive — one of the unfortunate consequences of declarative `import` over imperative `require`.)

**Comment by gewentao** [comment]
@Rich-Harris Sorry for posting a comment in this archived session. 

However, I met the same issue when trying to migrate from webpack to rollup. 

Concretely, we were using webpack dllPlugin to bundle some npm modules (e.g. [cerebraljs](https://www.npmjs.com/package/cerebral)) into a single **broswer_dll.bundle.js**. But now we met the `module declared after it's needed` issue when bundling cerebraljs. It seems that I need to mark cerebral as external as you suggested but I have no idea how should I tell rollup where to find `cerebral` when hitting `import cerebral from 'cerebral'`. Should I using a <script> tag with a CDN src url of cerebral? or something like webpack dll?
