### ISSUE TITLE
Undefined plugins crash rollup-plugin-commonjs

### ISSUE THREAD

**Issue by tivac** [rollup/rollup-plugin-commonjs#216]
(this is a follow-up to https://twitter.com/tivac/status/898212886790549505)

This plugin tries to access `.resolveId` on a plugin entry w/o checking that it isn't `undefined` first, which then explodes in cases where a plugin entry is `undefined`.

https://github.com/rollup/rollup-plugin-commonjs/blob/f7602d9fdea3401508eeac8d339fae0e3d057c2a/src/index.js#L102-L104

This causes errors when trying to use the `process.env.ROLLUP_WATCH` variable like this:

```js
{
    ...
    plugins : [
        process.env.ROLLUP_WATCH && plugin()
    ]
}
```

since `process.env.ROLLUP_WATCH` is either `undefined` or `true`. Possible easy fix would be to always define that value?

<details><summary>JS Error Stack</summary><p>

```txt
[!] TypeError: Cannot read property 'resolveId' of undefined
TypeError: Cannot read property 'resolveId' of undefined
    at C:\Users\tivac\Documents\crucible-menu\node_modules\rollup-plugin-commonjs\dist\rollup-plugin-commonjs.cjs.js:681:17
    at Array.map (<anonymous>)
    at Object.options (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup-plugin-commonjs\dist\rollup-plugin-commonjs.cjs.js:680:6)
    at C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\dist\rollup.js:9746:41
    at Array.reduce (<anonymous>)
    at new Bundle (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\dist\rollup.js:9745:25)
    at Object.rollup (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\dist\rollup.js:10476:16)
    at build$1 (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\bin\rollup:3124:16)
    at config (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\bin\rollup:3369:11)
    at next (C:\Users\tivac\Documents\crucible-menu\node_modules\rollup\bin\rollup:2568:10)
```
</p></details>

**Comment by tivac** [comment]
I'll try to send a PR for this tonight, seems like a really small fix.

**Comment by tivac** [comment]
Bleh, ran into `rollup` itself also not allowing for plugins to be `undefined`.

https://github.com/rollup/rollup/blob/3c1b2ff319251c18cdde41ff8c805a4edc510258/src/Bundle.js#L36

Maybe this is just me trying to paddle upstream & I should just ensure that I always use `Boolean(process.env.ROLLUP_WATCH)`?

**Comment by Rich-Harris** [comment]
We could probably just change [this line](https://github.com/rollup/rollup/blob/3c1b2ff319251c18cdde41ff8c805a4edc510258/src/Bundle.js#L33), no?

```diff
-this.plugins = ensureArray( options.plugins );
+this.plugins = ensureArray( options.plugins ).filter( Boolean );
```

**Comment by tivac** [comment]
Probably, at the time I sent this I thought `rollup` already handled `undefined` values in the `plugins` array correctly. I'm not sure why though, since I was clearly mistaken.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
