### ISSUE TITLE
support protected identifiers

### ISSUE THREAD

**Issue by flying-sheep** [rollup/rollup-plugin-commonjs#22]
as it’s perfectly reasonable to do `exports.default = foo`, yet the transformed syntax is the illegal `export var default = connect.default`

probably coincides with #10, as the project in question was react-redux, which seems to be compiled with babel

**Comment by flying-sheep** [comment]
another problem is that apparently acorn doesn’t handle comments in function declarations or so…

```
function compileMap(/* lists... */) {
```

raises unexpected in `parseExprAtom`. both were found via this hack: https://github.com/rollup/rollup/issues/296#issuecomment-166328583

isn’t there better parsers than acorn? e.g. babylon? i guess the first comment is wrong code generation, but this comment is clearly a parser not coded to spec.

**Comment by Swatinem** [comment]
I’m also stumbled across this just now. The `export var default = X.default` trips up the rollup parser.

**Comment by flying-sheep** [comment]
that should be handled in a special way anyway, since babel AFAIK started to translate it that way (with an explicit member “exports.default = ...“ instead of directly as “module.exports = ...”

**Comment by Rich-Harris** [comment]
#16 fixes this – I've updated that branch in light of some more recent changes. @Victorystick if you get a chance to review it, should be good to merge?

**Comment by Rich-Harris** [comment]
@flying-sheep that's... very odd. Acorn should parse that comment just fine. Are you able to reproduce that specific bug separately?

**Comment by Rich-Harris** [comment]
I've released 2.1.0 with the fix. @flying-sheep I don't know if that parser error deserves a separate issue or if https://github.com/rollup/rollup/issues/296#issuecomment-166328583 covers it? Either way I'll close this as it's unrelated to the reserved identifiers thing
