### ISSUE TITLE
transform.js calling magic-string.overwrite with boolean last argument causing warning

### ISSUE THREAD

**Issue by jharris4** [rollup/rollup-plugin-commonjs#221]
These two lines in `src/transform.js` are causing warnings because they are passing booleans as the last argument to `magic-string`'s `overwrite` function.

https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L144
https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/transform.js#L156

```The final argument to magicString.overwrite(...) should be an options object. See https://github.com/rich-harris/magic-string```

It looks like the above lines in transform.js should be changed from:

```
magicString.overwrite( node.start, node.end, `${HELPERS_NAME}.commonjsGlobal`, true );```
magicString.overwrite( node.start, node.end, `'object'`, false );
```

to this:

```
magicString.overwrite( node.start, node.end, `${HELPERS_NAME}.commonjsGlobal`, { storeName: true } );```
magicString.overwrite( node.start, node.end, `'object'`, { storeName: false } );
```

I'd be happy to create a PR if the changes seem correct

**Comment by Rich-Harris** [comment]
yes, that's absolutely correct — a PR would be fantastic, thanks!

**Comment by jharris4** [comment]
PR #222

**Comment by kopax** [comment]
Is it possible to have a release with this please ? :)

**Comment by jharris4** [comment]
PR was merged, so closing the issue
