### ISSUE TITLE
Conflict detection/avoidance for "require" aliases

### ISSUE THREAD

**Issue by otsdr** [rollup/rollup-plugin-commonjs#232]
React 16 bundles now use rollup as well; this means some of them may contain aliased requires, which will clash with the ones generated by the local rollup.
Example:
[React 16.0.0.0, node_modules/react/cjs/react.development.js](https://npm.runkit.com/react/cjs/react.development.js?t=1506456013752)
```
var objectAssign$1 = require('object-assign');
var require$$0 = require('fbjs/lib/warning');
```

gets converted to

```
var objectAssign$1 = require$$0;
var require$$0 = warning_1;
```

, which is obviously invalid.

This situation could be avoided if the name candidates were tested for uniqueness while increasing the uid.
Alternatively, either the separator ($$) or the start uid (0) could be configurable in transform.js .

**Comment by otsdr** [comment]
I have attached a small project that exhibits this issue. The production build does not go through the code block that contains the conflicting variable.

> $ yarn --version
> 1.1.0
> $ nodejs --version
> v6.11.3
> $ npm --version
> 3.10.10
> $ yarn install
> (...)
> $ npm run-script build
> > boilerplate@0.1.0 build 
> > rollup -c
> ./src/index.tsx → ./dist/bundle.js...
> created ./dist/bundle.js in 3.3s

[repro.zip](https://github.com/rollup/rollup-plugin-commonjs/files/1334893/repro.zip)

**Comment by mbostock** [comment]
Tiny test case here: https://github.com/rollup/rollup/issues/1655#issuecomment-332337049

**Comment by lukastaegert** [comment]
Hi @mbostock et al, as it appears that @Rich-Harris is currently on an extended vacation with limited internet access and cannot release a new version to npm, I have set up a make-shift solution for anyone suffering from this bug. You can now
```bash
npm install github:rollup-plugin-commonjs@rollup/rollup-plugin-commonjs#bundled-v8.2.3
```
which should contain all necessary build artefacts.

**Comment by hansoksendahl** [comment]
Any ETA on an npm release? It took a lot of googling to get here.

**Comment by lukastaegert** [comment]
Unfortunately not. It seems @Rich-Harris is on extended vacation with limited internet access and I do not know who else can publish to npm. Until then I fear you need to stick with the github install.

**Comment by TristanVALCKE** [comment]
Work perfectly for me ! Thank for the set-up.

I hope this is not vacation around the world ?!

**Comment by mijamo** [comment]
It seems like `8.2.4` was published yesterday on NPM so it is now fine :)

**Comment by falconmick** [comment]
I'm getting 

`TypeError: Object(...) is not a function`

now, is this related?
