### ISSUE TITLE
RollupJS ES6 module can't get imported because of default not found for redux and redux-form

### ISSUE THREAD

**Issue by kopax** [rollup/rollup-plugin-commonjs#235]
I have made a package for my login form that use `react-redux` and [redux-form](https://github.com/erikras/redux-form/tree/v7.0.4/src/immutable).

Both `react-redux` and `redux-form` are peer dependencies.

- During the build of my rollup, I don't have any error message.

- When I try to import my package into a project I have:

> WARNING in ./node_modules/login-form/dist/login-form.es.js
7455:22-33 "export 'default' (imported as '_reactRedux') was not found in 'react-redux'

> WARNING in ./node_modules/login-form/dist/login-form.es.js
7505:17-23 "export 'default' (imported as '_redux') was not found in 'redux'

*I have never imported myself `redux` in my login form project.*

- This is how I imported `redux-form` in my project:

        import { Field, reduxForm } from 'redux-form/immutable';

This was bundled by rollup and that was present in my es module : 

    import _reactRedux from 'react-redux';
    import _redux from 'redux';

This is the list of my rollup dependencies

    "rollup": "^0.50.0",
    "rollup-plugin-babel": "^3.0.2",
    "rollup-plugin-cleanup": "^1.0.1",
    "rollup-plugin-commonjs": "^8.2.1",
    "rollup-plugin-inject": "^2.0.0",
    "rollup-plugin-json": "^2.3.0",
    "rollup-plugin-node-resolve": "^3.0.0",
    "rollup-plugin-replace": "^2.0.0",
    "rollup-plugin-uglify": "^2.0.1",
    "rollup-plugin-visualizer": "^0.3.1",
    "rollup-watch": "^4.3.1",

I must have done something wrong, but I don't  know what, I have tried to set **namedExports** in every possibility but it didn't really help. 

Note that `redux` and `react-redux` does not export `default` but only named. Isn't it supposed to work out of the box ?

**Comment by arkgast** [comment]
Hi I'm facing the same issue, did you find a solution for this?

**Comment by kopax** [comment]
@arkgast yes, I managed to solve my issue using 
It was a bit tricky.

First, I activated an option of node resolve module : 

```jsx
  nodeResolve({
    modulesOnly: true,
  }),
```

This activated an error message that really helped me to detect that what I needed to have in my external was `redux-form/immutable` and not `redux-form`.

Closing as it is fixed. Hope it help
