### ISSUE TITLE
Latest version (8.2.3) with React 16 support is not published yet to npm

### ISSUE THREAD

**Issue by yamafaktory** [rollup/rollup-plugin-commonjs#242]
Hi,

The latest version of the plugin hasn't been published yet to npm:

```sh
npm view rollup-plugin-commonjs version
8.2.1
```

Thanks for this awesome project!

**Comment by lukastaegert** [comment]
I know, unfortunately the only known person with npm write access is currently not available. In the meantime, you can
```bash
npm install rollup/rollup-plugin-commonjs#bundled-v8.2.3
```

**Comment by yamafaktory** [comment]
Ok, thank you👍. Feel free to close the issue, but I guess as other people can potentially face it, it should be better to keep it opened.

**Comment by lukastaegert** [comment]
I will certainly leave it open until then 👍

**Comment by lukastaegert** [comment]
Is released!
