### ISSUE TITLE
[regression] flow types causing syntax errors

### ISSUE THREAD

**Issue by Andarist** [rollup/rollup-plugin-commonjs#244]
Im not sure how this works internally, but today's release broke out build. It exits with:
```
[!] (commonjs plugin) SyntaxError: Unexpected token (5:23) in path/to/my/module/index.js
```
whereas it previously didnt.

The issue goes away if I reorder commonjs and babel plugins.

My setup is pretty standard:
**rollup.config.js**
```js
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import babel from 'rollup-plugin-babel'
import replace from 'rollup-plugin-replace'
import uglify from 'rollup-plugin-uglify'
import { list as babelHelpersList } from 'babel-helpers'

const env = process.env.NODE_ENV

const config = {
	output: {
		format: 'umd',
		name: 'MyModule',
		exports: 'named',
	},
	plugins: [
		replace({
			'process.env.NODE_ENV': JSON.stringify(env),
		}),
		nodeResolve({
			jsnext: true,
		}),
		commonjs(),
		babel({
			exclude: 'node_modules/**',
			plugins: ['external-helpers'],
			externalHelpersWhitelist: babelHelpersList.filter(helperName => helperName !== 'asyncGenerator'),
		}),
	],
}
if (env === 'production') {
	config.plugins.push(
		uglify({
			compress: {
				pure_getters: true,
				unsafe: true,
				unsafe_comps: true,
				warnings: false,
			},
		})
	)
}

export default config

```
**.babelrc**
```json
{
  "presets": [
    "./.babelrc.js"
  ]
}
```

**.babelrc.js**
```js
const modules = process.env.BABEL_ENV === 'cjs' || process.env.NODE_ENV === 'test' ? 'commonjs' : false

const presets = [['es2015', { loose: true, modules }], 'stage-2']

const plugins = ['transform-flow-strip-types']

module.exports = { presets, plugins }
```

**Comment by jsebfranck** [comment]
+1

**Comment by Andarist** [comment]
@jsebfranck Ive added a comment about how to fix this issue in your codebase after I've created the issue. Aint sure if you have seen it, but you may reorder commonjs and babel plugins to fix this.

**Comment by farwayer** [comment]
New version do not work with default `babel-preset-react` too.

**Comment by Andarist** [comment]
@farwayer that's because `babel-preset-react@6` includes `babel-preset-flow` which in order includes `babel-plugin-transform-flow-strip-types`

**Comment by alexanderby** [comment]
Same issue with `rollup-plugin-typescript` (`@alexlur/rollup-plugin-typescript` actually). It shows me `Unexpected token` when mets object spread in a JS file.

Had to switch to `rollup-plugin-commonjs@8.2.3`

**Comment by Andarist** [comment]
@alexanderby try reordering your plugins, should work

**Comment by alexanderby** [comment]
@Andarist Thanks, that works. I'm not sure why it worked for at least the last 6 months with wrong order.

**Comment by Andarist** [comment]
Latest release has started to parse ur js files (or has started to parse more) to retrieve some data about exports i guess. It didnt do that before so the unknown syntax (such as flow or typescript) didnt cause the problem. Had no time to dig deeper into that as its easy to fix on our side and the changes were made for some reason

**Comment by Akryum** [comment]
Try this: https://github.com/rollup/rollup-plugin-commonjs/issues/247#issuecomment-341140246

**Comment by digitalkaoz** [comment]
@Andarist it dindt works as expected here...

if `commonjs` comes first, it fails with an `unexpected token error` (if i remove it everything works fine, all modules are resolved properly)

but if i switch the plugins to `babel` first, everything seems to work, but modules arent resolved in the final bundle ;/ (i still have require calls in the final bundle)

how did you solved it correctly?

**Comment by digitalkaoz** [comment]
maybe @lukastaegert can bring in some light how to properly use commonjs+babel nowadays?!

**Comment by Andarist** [comment]
@digitalkaoz  From what I remember the `babel` plugin should come first and then the commonjs plugin. Can't say why it is failing in your case if you do not share a repository with the issue reproduced in it.

**Comment by digitalkaoz** [comment]
@Andarist sure thing: https://github.com/digitalkaoz/rollup-commonjs-babel-playground

**Comment by lukastaegert** [comment]
Thanks for the repo, that will really help 👍
I will have a look but it will probably take a few days, promised to do a few other things first 🙄

**Comment by Andarist** [comment]
For what's it worth - after some quick debugging session it seems to me that `require` is not recognized correctly as module to be requested, it doesn't land in any `resolveId` hook from what I see.

@digitalkaoz did it work before? version of the repo (separate branch?) with that setup working would be highly appreciated

**Comment by digitalkaoz** [comment]
@Andarist no i never get it working...

**Comment by digitalkaoz** [comment]
with the latest version it seems to be fixed, thanks @lukastaegert for your awesome work!

**Comment by whizkydee** [comment]
> Try this: [#247 (comment)](https://github.com/rollup/rollup-plugin-commonjs/issues/247#issuecomment-341140246)

This works perfectly.

**Comment by JounQin** [comment]
It sucks with `react-draggable` which publish output with `flow` sourcemaps, of course `ignore` options or `sourceMap` could hanle this, but it would be greater to skip this error automatically with a warning instead of an error.

@lukastaegert Any idea?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
