### ISSUE TITLE
Version 8.2.4 conflicts with the Babel plugin

### ISSUE THREAD

**Issue by Finesse** [rollup/rollup-plugin-commonjs#247]
I use Rollup via JS API this way:

Bundling script:
```js
const rollup = require('rollup'); // 0.50.0
const rollupBabel = require('rollup-plugin-babel'); // 3.0.2
const rollupNodeResolve = require('rollup-plugin-node-resolve'); // 3.0.0
const rollupCommonJS = require('rollup-plugin-commonjs');
const babelPresetES2016 = require('babel-preset-es2016'); // 6.24.1
const babelPresetES2017 = require('babel-preset-es2017'); // 6.24.1
const babelPluginTransformRestSpread = require('babel-plugin-transform-object-rest-spread'); // 6.26.0
const babelPluginExternalHelpers = require('babel-plugin-external-helpers'); // 6.22.0

rollup.rollup({
	input: 'scriptToBundle.js',
	context: 'window',
	plugins: [
		rollupNodeResolve({
			browser: true,
			extensions: ['.js', '.json']
		}),
		rollupCommonJS({
			sourceMap: false
		}),
		rollupBabel({
			presets: [babelPresetES2017, babelPresetES2016],
			plugins: [babelPluginTransformRestSpread, babelPluginExternalHelpers]
		})
	]
}).then(bundle => bundle.write({
	file: 'bundledScript.js',
	format: 'iife',
	indent: false
}));
```

Script to bundle:
```js
const obj1 = {fruit: 'orange', car: 'lada'};
const obj2 = {...obj1, music: 'jazz'}
```

When I use the rollup-commonjs plugin version 8.2.3, the bundling is run successfully. But when I use the rollup-commonjs version 8.2.4, the rollup-babel plugins ignores the rest spread transform, the rest spread operator (`{...obj}`) gets to Rollup and the bundling fails:

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token (2:14) in ~/scriptToBundle.js
    at error (~/node_modules/rollup/dist/rollup.js:185:14)
    at Promise.resolve.then.catch.err (~/node_modules/rollup/dist/rollup.js:9448:6)

npm ERR! Darwin 17.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/npm-debug.log
```

**Comment by frzi** [comment]
Same here. Though I'm using the babel-plugin-transform-react-jsx plugin for babel. I'm getting an `Unexpected token` the moment rollup-plugin-commonjs reaches JSX syntax. 

This occurs in 8.2.4 and still occurs in 8.2.6. Going back to 8.2.3 is the current work-around.

**Comment by Akryum** [comment]
I made it work by excluding the project source folder:

```js
cjs({
  exclude: 'src/**',
}),
```

**Comment by tdeekens** [comment]
The `exclude` option in a lerna setup does sadly not work for me. My plugins look as follows

```js
replace({
      'process.env.NODE_ENV': JSON.stringify(env),
      VERSION: `'${version}'`,
    }),
    globals(),
    builtins(),
    resolve({
      module: true,
      jsnext: true,
      main: true,
      preferBuiltins: true,
    }),
    commonjs({
      ignoreGlobal: true,
      exclude: ['packages/**'],
    }),
    babel({
      exclude: ['node_modules/**'],
      babelrc: true,
      runtimeHelpers: true,
    }),
    filesize(),
```

Anything wrong with this setup?

**Comment by FinesseRus** [comment]
@Akryum It works, thank you!

You can also use this setup:

```javascript
rollupCommonJS({
    include: 'node_modules/**'
});
```

The bug is still a bug though.

**Comment by enzy** [comment]
This is a critical issue for us in our build pipeline, how we can help to fix it? Other rollup plugins works fine.

**Comment by adrianheine** [comment]
Does this still occur with 8.3.0?

**Comment by tdeekens** [comment]
Yes it seems so. At least CI tells me on a Greenkeeper PR.

**Comment by adrianheine** [comment]
Did you try putting the babel plugin first?

**Comment by enzy** [comment]
This still occurs with 8.4.0

**Comment by lukastaegert** [comment]
Just to get a little more context:
* As of version `0.56.0`, rollup natively understands object rest spread while as of version `9.0.0` (which is actually more or less the same as `8.4.0` except that rollup is listed as a peer dependency), this plugin will re-use rollup's parser and should thus be able to handle object rest spread as well. Do you still experience this issue when using these versions?
* Otherwise if you are using unknown/future syntax that you transpile via babel, then the babel plugin must come before the CJS plugin because the CJS plugin needs to be able to parse files to do transformations. Do you still experience issues if you order your plugins
  ```javascript
  [rollupNodeResolve(), rollupBabel(), rollupCommonJS()]
  ```
  ?

**Comment by pgn-vole** [comment]
@lukastaegert  I have the problem even with the correct ordering.

**Comment by ItsTarik** [comment]
@lukastaegert that's right, it worked for me(i use jsx) :ok_hand:

**Comment by Finesse** [comment]
Still actual for:
* rollup v0.66.4
* rollup-plugin-babel v4.0.3
* rollup-plugin-commonjs v9.1.8
* @babel/core v7.1.2

**Comment by Finesse** [comment]
@lukastaegert Changing the order of plugins solves the problem. Thank you!
