### ISSUE TITLE
Wrong bundle including readable-stream for the browser.

### ISSUE THREAD

**Issue by diegocr** [rollup/rollup-plugin-commonjs#248]
Hello,

First of all, it's my first time using rollup so i hope i'm posting this on the right repository...

Seems I'm facing some odd issue including [readable-stream](https://github.com/nodejs/readable-stream) targeting a **browser** build.

I've created a repro here: https://github.com/diegocr/rollup-stream-issue-repro

This is the simple input file:

https://github.com/diegocr/rollup-stream-issue-repro/blob/3f78a2ecd6229e6727c2947debee01f9539bce28/test.js#L2-L6
```js
var Readable = require('stream-browserify').Readable;

module.exports = function main() {
    console.log('Hello world.', Readable);
};
```

Note i'm intentionally relying on [stream-browserify](https://github.com/substack/stream-browserify) and not on the usual `stream` to prevent [rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins) from injecting their rather [outdated](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/tree/master/src/es6/readable-stream) version of [readable-stream](https://github.com/nodejs/readable-stream)

The generated build does then contains this ordering issue:

https://github.com/diegocr/rollup-stream-issue-repro/blob/3f78a2ecd6229e6727c2947debee01f9539bce28/bundle.js#L3917

```js
/*<replacement>*/
util.inherits = inherits_browser;
/*</replacement>*/

util.inherits(Duplex$1, _stream_readable);
```

However, that `_stream_readable` is declared some lines later:

https://github.com/diegocr/rollup-stream-issue-repro/blob/3f78a2ecd6229e6727c2947debee01f9539bce28/bundle.js#L4291

needless to say, running this throws an error..

The original code that is derived from is at:

https://github.com/nodejs/readable-stream/blob/56d9356637b5d20aba8e8e26faa602222f8500ab/lib/_stream_duplex.js#L50-L53

```js
/*<replacement>*/
var util = require('core-util-is');
util.inherits = require('inherits');
/*</replacement>*/

var Readable = require('./_stream_readable');
var Writable = require('./_stream_writable');

util.inherits(Duplex, Readable);
```

So, there are some `require()` calls that are just removed, which i think should be replaced by `import`s or whatever magic that happens under the hood.

**Comment by aphex** [comment]
Having the same issue using the mysql package which uses stream_duplex at some point. Any idea what is causing this?

**Comment by adrianheine** [comment]
There are circular dependencies. `stream-browserify` depends on `readable-stream/readable.js`, which `require`s `stream` (in your setup, that's `rollup-plugin-node-builtins/src/es6/stream.js`), which uses `rollup-plugin-node-builtins/src/es6/readable-stream/duplex.js`, which has a cycle with `rollup-plugin-node-builtins/src/es6/readable-stream/readable.js`. This is afaik not a `rollup-plugin-commonjs` issue.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
