### ISSUE TITLE
namedExports suggestion

### ISSUE THREAD

**Issue by GordonSmith** [rollup/rollup-plugin-commonjs#256]
Having to supply the full path to namedExports can be problematic as its somewhat dependent on how a users machine is configured.  It would be preferable to simply supply the package ID like we do in globals or externals:

Current:
```
            namedExports: {
                "../../node_modules/dagre/index.js": ["graphlib", "layout"]
            }
```
Preferable:
```
            namedExports: {
                "dagre": ["graphlib", "layout"]
            }
```

**Comment by zerkalica** [comment]
May be add regexp?

Same problem, i use ``` lerna bootstrap --hoist ```

This not works:

```
namedExports: {
                "react": ["createElement"]
            }
```
```
            namedExports: {
                "../../node_modules/react/index.js": ["createElement"]
            }
```

**Comment by bterlson** [comment]
Module names should work; re-open if that's not the case still.
