### ISSUE TITLE
A *new* "is not exported by" error

### ISSUE THREAD

**Issue by kuraga** [rollup/rollup-plugin-commonjs#262]
Good day!

If I'm trying to use
* *CommonJS packages* (with `module.exports = <...>;` inside)
* through `"lodash.concat": "file:<path-outside-node_modules>"` in `package.json`

I get errors:

```
[!] Error: 'default' is not exported by ../lodash.concat/index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
index.js (1:7)
1: import concat from 'lodash.concat';
          ^
```

But I don't get errors if package uses ECMAScript modules instead.

Or, another: I don't get errors if I don't use `file:` / put package into `node_modules`.

Why?

Thanks!

**Comment by jasonkarns** [comment]
same here. I'm trying to load a CJS module that's local to my package (we're migrating from CJS to ESM, so the ESM entrypoint that is compiled with rollup, is attempting to import from local CJS modules that are yet to be converted)

**Comment by adrianheine** [comment]
Can you show a complete repository or JavaScript file and rollup config?

**Comment by jasonkarns** [comment]
@adrianheine after doing some digging making the minimal repro, i think there are different issues at place, so i'm going to open a separate issue. and I'm pretty sure it actually belongs under rollup now, not this commonjs plugin...

**Comment by kuraga** [comment]
@jasonkarns thanks for investigation!

@adrianheine , https://github.com/kuraga/rollup-commonjs-is_not_exported_by-issue, run `./node_modules/.bin/rollup -c`. Thanks!

**Comment by kuraga** [comment]
Any ideas?

**Comment by rmariuzzo** [comment]
Just hit that same issue today.

**Comment by kuraga** [comment]
@lukastaegert , can you please help to investigate: is it a rollup-plugin-commonjs's or Rollup's issue?

**Comment by adrianheine** [comment]
@kuraga You pass `include: /node_modules/` to `rollup-plugin-commonjs`, which makes it skip `other_package`.

**Comment by kuraga** [comment]
@adrianheine @lukastaegert , really :-(. Sorry my stupid brain...

I just used a symlink in my application (so the symlink was *inside* `node_modules` so I didn't have this in mind...
