### ISSUE TITLE
'unionBy' is not exported by node_modules\lodash\lodash.js

### ISSUE THREAD

**Issue by randyaa** [rollup/rollup-plugin-commonjs#266]
going through an ng5 upgrade which required me to bump up rollup and the associated plugins. After doing so i'm getting this:

```
[!] Error: 'unionBy' is not exported by node_modules\lodash\lodash.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
dist\esm5\tr-ng-authorization.js (4:59)
2: import { Router } from '@angular/router';
3: import { Observable as Observable$1 } from 'rxjs/Observable';
4: import { endsWith, find, forEach, includes, reduce, union, unionBy } from 'lodash';
                                                              ^
5: import { BrowserXhr, Headers, Http, HttpModule, RequestOptions, XHRBackend } from '@angular/http';
6: import 'rxjs/add/operator/map';
```

My rollup config:

```
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import sourcemaps from 'rollup-plugin-sourcemaps';

// Add here external dependencies that actually you use.
const globals = {
    '@angular/core': 'ng.core',
    '@angular/common': 'ng.common',
    'rxjs/Observable': 'Rx',
    'rxjs/Observer': 'Rx',
    'rxjs/add/operator/map': 'Rx'
};

export default {
    external: Object.keys(globals),
    plugins: [
        resolve(),
        sourcemaps(),
        commonjs({
            namedExports: {
                'node_modules/lodash/index.js': [
                    'unionBy',
                    'union',
                    'reduce',
                    'find',
                    'forEach',
                    'includes',
                    'endsWith'
                ]
            }
        })
    ],
    onwarn: () => { return },
    output: {
        format: 'umd',
        name: 'ng.moduleNameHere',
        globals: globals,
        sourcemap: true,
        exports: 'named'
    }
}
```

**Comment by randyaa** [comment]
adding
`lodash: 'lodash'` to globals fixed the problem

**Comment by adrianheine** [comment]
In your `namedExports` config option, you use `node_modules/lodash/index.js`, but `lodash`'s `main` is `node_modules/lodash/lodash.js`. Fixing the config resolves the issue for me.

**Comment by scarnes54** [comment]
What if we run into this problem today? I don't have a rollup config to work with, so what are the steps to fix this? I am getting the issue on import isFunction.

**Comment by andresmijares** [comment]
im having a similar problem, have anyone been able to solve this?

**Comment by rmariuzzo** [comment]
@andresmijares I solved using something like:

```js
      commonjs({
        include: /node_modules/,
        namedExports: {
          'node_modules/lodash/index.js': ['get'],
        }
      }),
```

Where 'get' is the named export.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
