### ISSUE TITLE
global is undefined

### ISSUE THREAD

**Issue by stkevintan** [rollup/rollup-plugin-commonjs#277]
when I import `lunr` and trigger the `lunr.utils.warn` function , the  'warn' will be an error in browser environment. because `global` is not defined.

```js
lunr.utils.warn = (function (global) {
  /* eslint-disable no-console */
  return function (message) {
    if (global.console && console.warn) {
      console.warn(message);
    }
  }
  /* eslint-enable no-console */
})(this);
```

**Comment by stkevintan** [comment]
oh, I know in strict mode , this will be replaced by undefined. wtf....

**Comment by DanielRuf** [comment]
> oh, I know in strict mode , this will be replaced by undefined. wtf....

Right. And here we need something like
```
if(global === undefined && window !== undefined) global = window
```

Why was this closed?

**Comment by stkevintan** [comment]
@johnlim I give up to pack lunr into my bundle resources. just use the old way: script html tag

**Comment by johnlim** [comment]
@stkevintan Did you consider using webpack instead?

**Comment by lukastaegert** [comment]
There was a PR in rollup but there were some issues with it so it was stalled. If someone were to pick it up again, this would be great.
