### ISSUE TITLE
Breaks elliptic on compile

### ISSUE THREAD

**Issue by AlbertoElias** [rollup/rollup-plugin-commonjs#278]
One of my dependencies has a sub-dependency that's https://www.npmjs.com/package/elliptic which I'm unable to to use after compiling with rollup. The runtime error I get is `TypeError: elliptic_1 is undefined`.

This is my rollup config:

```
rollup({
		input: 'main.js',
		plugins: [
			commonJS({
				ignoreGlobal: true
			}),
			json(),
			globals(),
			builtins(),
			nodeResolve({
				preferBuiltins: false,
				browser: true
			})
		]
}).then((bundle) => {
		return bundle.write({
			format: 'iife',
			name: 'test',
			file: 'build/main.js'
		});
}).catch(console.log);
```

Any suggestions? Thanks!

**Comment by imerkle** [comment]
same

**Comment by ClemensLey** [comment]
Does anyone have an idea for how to fix this?

**Comment by Arctek** [comment]
See - https://github.com/rollup/rollup/issues/1507

There is a forked version at https://github.com/xg-wang/elliptic, which replaces the circular dependencies. 

My issue is that elliptic is used in over 28 other packages in my project, and the dependency needs to be updated for all of them.

**Comment by ldub** [comment]
To anybody who finds this from google, one workaround is to first run webpack on elliptic.js and then feed it through rollup:

**webpack.elliptic.js**
```javascript
const path = require('path');

module.exports = {
    entry: {
        "elliptic": path.resolve(__dirname, "node_modules/elliptic/lib/elliptic.js")
    },
    output: {
        filename: 'elliptic.js',
        library: "elliptic",
        libraryTarget: 'commonjs2',
        path: path.resolve(__dirname, "includes")
    },
    mode: 'production',
    optimization: {
        minimize: false,
    }
};
```

**rollup.config.js**
```javascript
...
import alias from 'rollup-plugin-alias';
...
        plugins: [
            alias({
                elliptic: path.resolve(__dirname, 'includes/elliptic.js')
            }),
        ];
```

**package.json**
```
  "scripts": {
    "build": "npm run build:elliptic && npm run build:rollup",
    "build:elliptic": "webpack --config webpack.elliptic.js",
    "build:rollup": "rollup -c"
  }
```


The reason this works is that webpack handles circular dependencies differently and is less strict. This probably results in a far less optimal build of your code but at least it works.

Thanks to @iantanwx for implementing and sharing this solution originally: https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/a197f6fb5f109606b5933d6a382eb987d7a4e88f/scripts/bundle.ts#L21-L27

**Comment by shrpne** [comment]
@Arctek you can make 'npm install github:xg-wang/elliptic' and all your project elliptic deps should be replaced with it. To check it you can `npm list elliptic` and see what elliptic package is used for your deps

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
