### ISSUE TITLE
Rollup experimentalCodeSplitting

### ISSUE THREAD

**Issue by jthoms1** [rollup/rollup-plugin-commonjs#282]
With the release of `rollup@0.55.0` a new flag was created called `experimentalCodeSplitting`. This allows for a new code splitting mechanism that allows rollup to accept multiple entry points.  It appears that this plugin is currently not compatible with this flag.  I think it is a fair assumption many rollup users depend on this plugin.

Currently resolveId is used to gather the full path of the entry point file and it is then used to compare against the transform function.  It appears this is a simple update to allow for arrays or strings.  Would you be amenable to accepting a PR to fix this issue.

**Path Resolution of a single filePath**
https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/index.js#L136

**Comparison**
https://github.com/rollup/rollup-plugin-commonjs/blob/master/src/index.js#L185

**Comment by lukastaegert** [comment]
Resolved via #283
