### ISSUE TITLE
Make named exports automatic

### ISSUE THREAD

**Issue by zwhitchcox** [rollup/rollup-plugin-commonjs#290]
So, I haven't really looked into this to see if it's possible, because I feel like this is probably going to be rejected anyway, but having to add stuff like this

```js
      namedExports: {
        'node_modules/react/react.js': ['Children', 'Component', 'PropTypes', 'createElement'],
        'node_modules/react-dom/index.js': ['render']
      }
```

is a pretty huge barrier to entry for most people. I don't think anyone really wants to have to do this. Is there anyway we can make this automatic? It's just a stumbling block for anyone starting out with rollup, IMO.

I'm more than happy to do a PR if it will be accepted.

**Comment by zerkalica** [comment]
May be this semi-automatic workaround helps:

```js
import path from 'path'
import fs from 'fs'
import nodeEval from 'node-eval'

export function getModuleExports(moduleId) {
    const id = require.resolve(moduleId)
    const moduleOut = nodeEval(fs.readFileSync(id).toString(), id)
    let result = []
    const excludeExports = /^(default|__)/
    if (moduleOut && typeof moduleOut === 'object') {
        result = Object.keys(moduleOut)
            .filter(name => !excludeExports.test(name))
    }

    return result
}

export function getNamedExports(moduleIds) {
    const result = {}
    moduleIds.forEach( id => {
        result[id] = getModuleExports(id)
    })
    return result
}
```

Usage:
```
{
        commonjs({
            namedExports: getNamedExports(['react', 'react-text-mask', 'react-dom'])
        }),
}
```

**Comment by OlzhasAlexandrov** [comment]
@zerkalica 
Thank you for making to think in the positive direction.
I just tried to use your example on a [graphql](https://github.com/graphql/graphql-js) dependency, it did find them, but couldn't resolve the error:
```js
// rollup config
  commonjs({
    include: "node_modules/**",
    sourceMap: false, // Default: true
    namedExports: getNamedExports(["graphql"]),
  }),
```
```js
// console.log of the resulting object of getNamedExports
{ graphql:
   [ 'graphql',
     'graphqlSync',
     'GraphQLSchema',
     'GraphQLScalarType',
     'GraphQLObjectType',
     'GraphQLInterfaceType',
     'GraphQLUnionType',
     'GraphQLEnumType',
     'GraphQLInputObjectType',
     'GraphQLList',
     ... ~110 more items ] }
```
```js
// still the same error
Error: 'GraphQLObjectType' is not exported by node_modules/graphql/type/index.js
36: export { GraphQLSchema, // Definitions
37: GraphQLScalarType, GraphQLObjectType, GraphQLInterfaceType, GraphQLUnionType, GraphQLEnumType, GraphQLInputObjectType, GraphQLList, GraphQLNonNull, GraphQLDirective, // "Enum" of Type Kinds
                       ^
38: TypeKind, // Scalars
39: specifiedScalarTypes, GraphQLInt, GraphQLFloat, GraphQLString, GraphQLBoolean, GraphQLID, // Built-in Directives defined by the Spec
```

**Comment by zerkalica** [comment]
Looks like graphql has an es6 export module version. namedExports unnecessary here.

**Comment by OlzhasAlexandrov** [comment]
Using `.mjs` version brought other issues:
```js
  // https://github.com/rollup/rollup-plugin-node-resolve
  resolveNode({
    module: true,
    extensions: [".mjs", ".js", ".jsx", ".json"], // Default: [ '.mjs', '.js', '.json', '.node' ]
    jsnext: true,
    preferBuiltins: false,
    customResolveOptions: {
      moduleDirectory: paths.currentProject("node_modules"),
    },
  }),
  // https://github.com/rollup/rollup-plugin-commonjs
  commonjs({
    include: "node_modules/**",
    exclude: ["node_modules/graphql/**"], // Default: undefined

    sourceMap: false, // Default: true
  })
```
```js
// error
!) Missing exports
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
commonjs-proxy:./node_modules/graphql/index.mjs
default is not exported by node_modules/graphql/index.mjs
1: import * as graphql from "./node_modules/graphql/index.mjs"; export default ( graphql && graphql['default'] ) || graphql;

**Comment by gaberudy** [comment]
For those following the breadcumbs of why graphql can't be used with rollup, although the index.mjs file is loaded from graphql, it re-exports from a bunch of sub-modules, each of which has both a `index.js` and a `index.mjs` file.

rollup seems to always check for index.js first and use it if it exists.

My solution, pre-running rollup, I do:

```
rm   node_modules/graphql/*/index.js
```
which allows rollup to pick up the index.mjs files and then it can find all of it's imports

I think the fix would be to prefer the `index.mjs` for when it exists alongside a `index.js`!

**Comment by chpio** [comment]
<https://github.com/rollup/rollup-plugin-commonjs/issues/290#issuecomment-378584955>

Is there a way to put this in a separated resolve plugin? maybe it could then resolve sub-dependencies? Right now that's not possible, it can't resolve eg `node_modules/my_package/node_modules/react`.

**Comment by kalbert312** [comment]
@zerkalica thanks I will need to try that snippet. I'm trying to convert a react component lib from webpack to rollup but I ran into this with basically every React import and it's a huge turn-off to manually maintain import whitelist in rollup config. I am having a pleasant experience with rollup in some of my smaller packages though but as the original comment mentions it's a barrier to entry that did a pretty good job of almost scaring me off.

**Comment by TrySound** [comment]
@kalbert312 Try this
```js
import * as react from 'react';
import * as reactDom from 'react-dom';
import * as reactIs from 'react-is';
import * as propTypes from 'prop-types';

export default {
  ...
   plugins: [
    ...
    commonjs({
      namedExports: {
        react: Object.keys(react),
        'react-dom': Object.keys(reactDom),
        'react-is': Object.keys(reactIs),
        'prop-types': Object.keys(propTypes),
      },
    }),
  ]
}


```

**Comment by kalbert312** [comment]
Thanks, that resolved my issue. Out of curiosity, Is this a consequence of growing pains moving away from CommonJS?

**Comment by GongT** [comment]
```javascript
import { Script } from 'vm';
import { createRequire } from 'module';

const namedExports = {};

function mergeNamedExports(missingFile) {
	const script = new Script('const m = require(missingFile.replace(/^node_modules\\//, ""));namedExports[missingFile] = Object.keys(m);');
	return script.runInNewContext({ require: createRequire(__filename), namedExports, missingFile });
}

mergeNamedExports("xxxxxxxxx");
mergeNamedExports("yyyyyyyyy");

export default {
	plugins: [
		// ...
		commonjsPlugin({
			extensions: ['.esm.js', '.mjs', '.js', '.ts'],
			namedExports,
		}),
		// ...
	]
};
```

### When you see error:
> [!] Error: 'decode' is not exported by node_modules/draft-js/lib/DraftOffsetKey.js

### You write:
```
mergeNamedExports("node_modules/draft-js/lib/DraftOffsetKey.js");
```

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:

**Comment by zwhitchcox** [comment]
@shellscape This issue is still relevant

**Comment by TrySound** [comment]
@zwhitchcox There is nothing to do here. Wait when react will land esm support.
