### ISSUE TITLE
The order of common and buble

### ISSUE THREAD

**Issue by lukejacksonn** [rollup/rollup-plugin-commonjs#295]
I used to have a config that had plugins configured as follows:
```js
plugins: [
  resolve(),
  commonjs(),
  buble({ jsx: 'h' }),
]
```
Which used to work great, but recently I have encountered some `Unexpected Token` errors if files contain JSX; this prevents projects for building entirely.

After some investigation it seems that re-ordering the plugins (moving buble before commonjs) solves the issue (most of the time).

```js
plugins: [
  resolve(),
  buble({ jsx: 'h' }),
  commonjs(),
]
```

But causes issues when importing commonjs modules.

Is this a known issue and is there anything I can do to make the original config work again?

**Comment by aleclarson** [comment]
Try enabling only the `jsx` transform for the `buble` plugin *before* `commonjs`.

Then you can put a plain `buble()` call *after* `commonjs`.

**Comment by lukejacksonn** [comment]
Cool, thanks.. I will give this a try!

**Comment by lukejacksonn** [comment]
This worked.. but feels like a horrible hack. What is puzzling me is; what changed in which version that made this just _not work_ one day. When I get time I will start rolling back the versions of various dependencies until I find the culprit.

**Comment by lukastaegert** [comment]
The issue is that rollup-plugin-commonjs needs to parse the file in order to determine if it is a commonjs file. In order for this to work, it needs to be a valid JS file. This is why moving bublé first solves the invalid token issue. I wonder what transformation causes the issues when bublé is run before the CJS plugin, though.

**Comment by lukejacksonn** [comment]
Yeh.. so when you do bublé after commonjs you get `Unexpected Token: < at line X` whenever it comes across some JSX. That makes sense because it doesn't know about that syntax. So.. you put bublé before commonjs and by the time commonjs gets to that file, all the JSX has already been converted to `h` or `createElement`. Great.

The problem is now.. I can't remember what issue I was having with commonjs modules, when bublé is run before the CJS plugin 😅

**Comment by lukastaegert** [comment]
No problem. If you remember it might be interesting to look into this a little deeper. These plugin-order issues are definitely a pain and we hope to improve at some point.

**Comment by bterlson** [comment]
This seems resolved, but please re-open if that's not the case!
