### ISSUE TITLE
`addExtension` does not work for modules containing dots

### ISSUE THREAD

**Issue by Swatinem** [rollup/rollup-plugin-commonjs#3]
Experimenting with https://github.com/zloirock/core-js/issues/125, I came across the issue that core-js has file names like `$.a-function.js` which it imports using `.js`-free require calls.

That unfortunately breaks importing those modules and I had to work around that issue in my experiment.

**Comment by Rich-Harris** [comment]
Thanks - fixed in 1.1.0
