### ISSUE TITLE
Update changelog to 9.0.0

### ISSUE THREAD

**Issue by hpohlmeyer** [rollup/rollup-plugin-commonjs#301]
The last change that has been documented in the changelog is 8.4.0.  
Especially for 9.0.0 which seems to include breaking changes an updated changelog would help.

**Comment by lukastaegert** [comment]
I'll fix that, thanks.

**Comment by lukastaegert** [comment]
Done! So 8.4.1 was actually a re-release of 8.3.0 while 9.0.0 is 8.4.0 + rollup as a peer dependency.
