### ISSUE TITLE
Option to keep commonjs-external and commonjs-proxy out of generated source

### ISSUE THREAD

**Issue by lastmjs** [rollup/rollup-plugin-commonjs#305]
I'm using this plugin with the `experimentalPreserveModules` option. I'm just trying to get the source code for a single file converted from CommonJS to ES Modules without any kind of resolution. That will be handled elsewhere in my build process. 

I have the following output after running my input file through Rollup with this plugin:

```
import 'assert';
import 'lazy-seq';
import './api.js';
import './either.js';
import './environment.js';
import './finitemap.js';
import './fn.js';
import './functor.js';
import './random.js';
import './show.js';
import './shrink.js';
import './suchthat.js';
import './sum.js';
import './typify.js';
import './utils.js';
import assert from '../../../commonjs-external:assert.js';
import lazyseq from '../../../commonjs-external:lazy-seq.js';
import api from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/api.js';
import either from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/either.js';
import environment from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/environment.js';
import FMap from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/finitemap.js';
import fn from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/fn.js';
import functor from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/functor.js';
import random from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/random.js';
import show from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/show.js';
import shrink from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/shrink.js';
import suchthat from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/suchthat.js';
import sum from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/sum.js';
import typify from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/typify.js';
import utils from '../../../commonjs-proxy:/home/lastmjs/development/jsverify-bundled/node_modules/jsverify/lib/utils.js';
```

All of the `commonjs-proxy` and `commonjs-external` imports are irrelevant to me. Could we provide an option for getting rid of those?

**Comment by lastmjs** [comment]
I just realized that the first block of imports here don't actual import what I need...

**Comment by lastmjs** [comment]
It would be nice if there were an option to just convert CommonJS to ES Modules for use with the `experimentalPreserveModules` option. Is there any reason this can't be done?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
