### ISSUE TITLE
Can't process a particular package

### ISSUE THREAD

**Issue by probablyup** [rollup/rollup-plugin-commonjs#321]
Perhaps someone could shed some light on this...

I'm trying to upgrade styled-components from rollup-plugin-commonjs v3 or so to latest and it can't seem to understand this file: https://github.com/thysultan/stylis.js/blob/master/stylis.js

The code we're using is:

```js
import Stylis from 'stylis';
```

Which works fine in versions before `rollup-plugin-commonjs` v4. Any ideas?

I saw a bunch of issues around "namedImports" but this package doesn't use that, it's a true default export in CJS land.

**Comment by TrySound** [comment]
How about `rollup-plugin-commonjs` v9?

**Comment by probablyup** [comment]
I'll try it again when I get home, but I don't believe it was working.

**Comment by TrySound** [comment]
I just tried. It works for me.
