### ISSUE TITLE
 this$1.error is not a function

### ISSUE THREAD

**Issue by nerdynick** [rollup/rollup-plugin-commonjs#325]
Not sure whats going on but it looks like the error function used on the line below is never defined.

(node:8424) UnhandledPromiseRejectionWarning: TypeError: Error transforming .../node_modules/iab-vast-loader/index.js with 'commonjs' plugin: this$1.error is not a function
    at .../node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:829:12
    at <anonymous>

rollup-plugin-commonjs Version is 9.1.3

**Comment by nerdynick** [comment]
Digging farther the error starts out with the function parse() not being defined for this

Error effecting the promise:
TypeError: parse is not a function in .../node_modules/iab-vast-loader/src/index.js
    at tryParse (../node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:194:10)
    at checkEsModule (.../node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:207:12)
    at .../node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:803:15
    at <anonymous>

**Comment by lukastaegert** [comment]
It looks like your rollup version may be out of date. Both the error handler and the parse function are very recent additions to rollup.
