### ISSUE TITLE
Cannot bundle with google cloud modules

### ISSUE THREAD

**Issue by mackenzie-orange** [rollup/rollup-plugin-commonjs#335]
I am getting an error when trying to build a super simple library using the google cloud modules. 

I have not gotten this error with any other module. Sometimes it will switch between showing pubsub and datastore as the issue (always the same general error). I am uncertain if this is a rollup-plugin-commonjs problem or a google cloud problem. I am happy to move this issue to another repo if we find rollup-plugin-commonjs is not the issue. 

```
index.js → out/app.js...
[!] Error: Unexpected token
node_modules/@google-cloud/pubsub/package.json (2:9)
1: {
2:   "_from": "@google-cloud/pubsub",
            ^
3:   "_id": "@google-cloud/pubsub@0.19.0",
4:   "_inBundle": false,
```

--------------------------------

Reproduce with:

Install things:
`mkdir proj && cd proj && npm init -y && npm i -D rollup rollup-plugin-node-resolve rollup-plugin-commonjs`

Install dependencies:
`npm i @google-cloud/pubsub @google-cloud/datastore`

Make the files:
```
// rollup.config.js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default [
    {
        input: 'index.js',
        output: {
            name: 'app',
            file: 'out/app.js',
            format: 'umd'
        },
        plugins: [
            resolve(),
            commonjs() 
        ]
    },
];
```

```
// index.js:
var lodash = require('lodash')
var PubSub = require('@google-cloud/pubsub');
var Datastore = require('@google-cloud/datastore');
```

Run with this command
`npx rollup -c`

**Comment by lukastaegert** [comment]
It looks like the module is trying to import a JSON file. This error is probably not triggered by rollup-plugin-commonjs but by rollup itself. Try adding rollup-plugin-json to your config.

**Comment by mackenzie-orange** [comment]
Thanks, I believe that solves the issue!
