### ISSUE TITLE
Regression in 9.1.1 - Using cache will cause the next compilation to freeze

### ISSUE THREAD

**Issue by porsager** [rollup/rollup-plugin-commonjs#337]
More info here: https://github.com/rollup/rollup/issues/2371

**Comment by guybedford** [comment]
Thanks for tracking this down, if you're able to look into it and make any suggestions that would be a great help, otherwise I will look into this soon.

**Comment by porsager** [comment]
Already made this PR ;) https://github.com/rollup/rollup-plugin-commonjs/pull/338

**Comment by guybedford** [comment]
Ah, perfect! Thanks.
