### ISSUE TITLE
Does not work with non-strict CommonJS modules

### ISSUE THREAD

**Issue by Pauan** [rollup/rollup-plugin-commonjs#34]
I created a gist with all of the relevant information:

https://gist.github.com/Pauan/6b58b7fca0ed0648a8f4

The file `bar.js` is the entry point, and `output.js` is the compiled bundle.

When using the `rollup-plugin-commonjs` plugin, it converts `foo.js` into an ES6 module and inserts it into the bundle.

The problem is that the bundle contains `'use strict';` at the top, which causes the following error in Chrome:

```
Uncaught TypeError: Cannot assign to read only property 'name' of function 'function foo() {}'
```

Essentially, the issue is that `foo.js` relies upon non-strict behavior, therefore it fails because the bundle is always in strict mode.

I found this error when trying to use [virtual-dom](https://github.com/Matt-Esch/virtual-dom) with rollup, because some of their CommonJS modules do not work in strict mode.

One potential solution to this problem is to use two immediately-executed-function-expressions: an outer function for all of the CommonJS modules, and an inner function for all of the ES6 modules:

```
(function () {
	function __commonjs(fn, module) { return module = { exports: {} }, fn(module, module.exports), module.exports; }

	var foo = __commonjs(function (module) {
	// CommonJS, not strict mode
	function foo() {}
	foo.name = 5;

	module.exports = foo;
	});

	(function () {
		'use strict';

		var foo$1 = (foo && typeof foo === 'object' && 'default' in foo ? foo['default'] : foo);

		foo$1();

	}());
}());
```

**Comment by Rich-Harris** [comment]
Apologies for the eight month silence. This is a `wontfix` I'm afraid – ES modules are *always* strict, so there's no correct way to convert a module that relies on non-strict behaviour. There's no good reason for code *not* to opt in to strict mode, so libraries should update accordingly (it looks like virtual-dom already did).

**Comment by matthiasg** [comment]
i am having issues like this too while using mocha/chai to write some tests. It seems it uses arguments/callee etc.

**Comment by arackaf** [comment]
This means Rollup is a non-starter for any legacy applications which rely use ejs templates, and rely on `with` behavior for parsing.
