### ISSUE TITLE
First pass test matches ES6 modules as CommonJS modules making namedExports unusable

### ISSUE THREAD

**Issue by qgustavor** [rollup/rollup-plugin-commonjs#36]
From the source [the first time test](https://github.com/rollup/rollup-plugin-commonjs/blob/fc4e80fd8ab1b0d493206ec8ead7511f2e98ae10/src/index.js#L10) detects using an simple regular expression could be a CommonJS module, trying to find expressions like "require" and "exports". As it's a simple test sometimes it matches those expressions in strings and comments (example: "required" from Apache License), making it try to transform the file as a CommonJS module. 

When transforming the file it ends up not finding any exports and normally it returns `null`, [except when `namedExports` is used](https://github.com/rollup/rollup-plugin-commonjs/blob/fc4e80fd8ab1b0d493206ec8ead7511f2e98ae10/src/index.js#L188). Maybe it can be changed to a warning and/or the first pass test me improved in some way to ignore strings and comments.

**Comment by Rich-Harris** [comment]
Thanks! Was a simple typo – fixed in 2.2.1.
