### ISSUE TITLE
_uid is not a function by createCommonjsModule

### ISSUE THREAD

**Issue by lishengzxc** [rollup/rollup-plugin-commonjs#360]
Hi, gays

I use `rollup-plugin-node-resolve` `rollup-plugin-commonjs` `rollup-plugin-node-builtins` together.

The source code is like this

```js
import Events from 'events';

export default function helloworld() {
  console.log(Events);
  console.log('helloworld');
}
```

And The `rollup.config.js` is like this

```js
import babel from 'rollup-plugin-babel';
import replace from 'rollup-plugin-replace';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import builtins from 'rollup-plugin-node-builtins';
import globals from 'rollup-plugin-node-globals';
import json from 'rollup-plugin-json';

export default {
    input: 'src/index.js',
    output: {
      file: 'build/index.js',
      format: 'umd',
      name: 'HelloWorld',
      globals: {},
    },
    external: [],
    plugins: [
      globals(),
      builtins(),
      resolve(),
      commonjs(),
      json(),
      babel({
        exclude: 'node_modules/**',
        babelrc: false,
        presets: [
          [
            require.resolve('@babel/preset-env'),
            {
              'useBuiltIns': 'usage',
              'targets': 'chrome >= 49',
            }
          ],
          require.resolve('@babel/preset-react')
        ],
        plugins: [
          require.resolve('@babel/plugin-proposal-class-properties'),
          [
            require.resolve('@babel/plugin-proposal-decorators'),
            {
              legacy: true,
            }
          ]
        ]
      }),
      
      replace({
        'process.env.NODE_ENV': JSON.stringify('production')
      }),
    ]
  }
```

Unfortunately，the code run in Browser throw this error

```js
index.js:174 Uncaught TypeError: _uid is not a function
    at index.js:174
    at createCommonjsModule (index.js:10)
    at index.js:173
    at index.js:4
    at index.js:5
```

![](https://gw.alicdn.com/tfs/TB15foGrFzqK1RjSZFCXXbbxVXa-634-141.png)

When I review the build/index.js, I find the order of code maybe has some error.

I try to modify the order of code then there no errors

**I move this code forward**
![](https://gw.alicdn.com/tfs/TB1StgErSzqK1RjSZFHXXb3CpXa-1061-1007.png) 

![](https://gw.alicdn.com/tfs/TB1Ep7HrFzqK1RjSZFCXXbbxVXa-947-964.png)

Is there any way to solve this problem automatically?

this is the `build/index.js` https://github.com/lishengzxc/bblog/issues/42

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:
