### ISSUE TITLE
[!] Error: 'default' is not exported by ../../node_modules/prop-types/index.js

### ISSUE THREAD

**Issue by xianshannan** [rollup/rollup-plugin-commonjs#361]
rollup config
```js
// rollup.config.js
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'umd',
    name: umdName,
    indent: false,
    sourcemap: false,
  },
  plugins: [
    nodeResolve(),
    commonjs({
      include: 'node_modules/**', // Default: undefined
    }),
  ],
};

```
When running `rollup -c`,it will throw the error.
I have been looking for this problem for a while, but there is no solution.
But when using commonjs without any options,it wok fine.
```js
// rollup.config.js
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'umd',
    name: umdName,
    indent: false,
    sourcemap: false,
  },
  plugins: [
    nodeResolve(),
    commonjs(),
  ],
};

```

**Comment by TrySound** [comment]
@xianshannan Do you have monorepo?

**Comment by TrySound** [comment]
Try `/node_modules/` regexp

**Comment by xianshannan** [comment]
@TrySound I don't use monorepo.
I had try `/node_modules/`，but `namedExports` did not work.
It throws the error:
`[!] Error: 'isValidElementType' is not exported by ../../node_modules/react-is/index.js`
```js
// rollup.config.js
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve';

export default {
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'umd',
    name: 'umdName',
    indent: false,
    sourcemap: false,
  },
  plugins: [
    nodeResolve(),
    commonjs({
      namedExports: {
        'node_modules/react-js/index.js': ['isValidElementType'],
      },
      include: [
        /node_modules\/prop-types/,
        /node_modules\/hoist-non-react-statics/,
        /node_modules\/invariant/,
        /node_modules\/react-is/,
        /node_modules\/warning/,
      ],
    }),
  ],
};
````

**Comment by TrySound** [comment]
I use names which I import from
```
      namedExports: {
        'react-js': ['isValidElementType'],
      },
```

**Comment by xianshannan** [comment]
@TrySound Thanks, it did work.

**Comment by NathanielHill** [comment]
@TrySound Thanks for this! Finally realized my node modules being `../../` down from rollup's `cwd` was causing most of my problems!

**Comment by NathanielHill** [comment]
I wonder if there should be a note in the docs about monorepos? Most tools play nice with different `node_modules` location

**Comment by josefaidt** [comment]
@NathanielHill I'm having this exact same issue with a monorepo. Came to rollup for a react component library and a note like that would be incredibly helpful.

**Comment by NathanielHill** [comment]
@josefaidt Did you fix your problem?

**Comment by NathanielHill** [comment]
I created a pull request to update the docs with a note: https://github.com/rollup/rollup-plugin-commonjs/pull/372

**Comment by josefaidt** [comment]
@NathanielHill No I have not. Using the `include: /node_modules/` property did not work unfortunately.

**Comment by NathanielHill** [comment]
@josefaidt You also need to be careful about whether `/node_modules/` is transpiled by babel or not. You can also use regexes there and I would advise that as well.

**Comment by josefaidt** [comment]
Ah that did it. Didn't think about the transpilation at first. I had to also add all of my dependencies to `externals` as shown below:

```js
export default {
  input: './src/index.js',
  output: {
    file: './build/bundle.js',
    name: 'SomeModule',
    format: 'iife',
    sourcemap: 'inline',
  },
  plugins: [
    babel({ plugins: babelPlugins, presets: babelPresets, exclude: /node_modules/ }),
    url(),
    postCss({ modules: true }),
    nodeResolve(),
    cjs({
      include: /node_modules/,
    }),
  ],
  external: ['react', 'react-dom', 'prop-types', 'styled-components'],
}
```

**Comment by NathanielHill** [comment]
:tada: Exactly! There's a plugin to generate the externals automatically from `package.json`, but it didn't work for me at all, and apparently it doesn't support namespaced packages.

Would be nice if that worked.

**Comment by josefaidt** [comment]
Yes, thank you for your timely assistance! Thankfully this will be a relatively small library in terms of packages used, but I agree it would be nice to do it automatically.

**Comment by sunyongjian** [comment]
+1

namedExports always is not work, I have tried all the above methods.

**Comment by zhaowenjian** [comment]
+1 , is this a bug ? the rollup-plugin-commonjs doc about namedExports not useful?

**Comment by bwhitty** [comment]
To go with https://github.com/rollup/rollup-plugin-commonjs/issues/361#issuecomment-445441389 and anyone else reading this (and maybe working in a monorepo), to fix `prop-types` fully, this works:

```js
commonjs({
  // https://github.com/rollup/rollup-plugin-commonjs#usage-in-monorepo
  include: /node_modules/,
  namedExports: {
    // node_modules/prop-types/factoryWithTypeCheckers.js#L115
    'prop-types': [
      'array',
      'bool',
      'func',
      'number',
      'object',
      'string',
      'symbol',
      'any',
      'arrayOf',
      'element',
      'elementType',
      'instanceOf',
      'node',
      'objectOf',
      'oneOf',
      'oneOfType',
      'shape',
      'exact',
    ],
  },
}),
```

Alternatively, and against the suggestions of `prop-types`'s, documentation, marking `prop-types` as a `peerDependency` (assuming you're bundling a package) and using `rollup-plugin-peer-deps-external` would work as well.

**Comment by AntonioRedondo** [comment]
I've been having an absolute inconsistent behaviour with the `commonjs` plugin and the `include` property. I had to play with these three values in order to Rollup to compile:
```javascript
commonjs({
    include: [
        "node_modules",
        "node_modules/**",
        "node_modules/**/*",
    namedExports: { ... },
}),
```
Don't put all three, just use the one that makes `namedExports` working, mostly `node_modules/**` and ` node_modules/**/*`.

**Comment by TrySound** [comment]
@AntonioRedondo RegEx is more universal here
```js
commonjs({
  include: /node_modules/,
  namedExports: { ... }
})
```
