### ISSUE TITLE
Issue trying to use in combination with ES6 classes compiled through rollup-plugin-babel

### ISSUE THREAD

**Issue by arendjr** [rollup/rollup-plugin-commonjs#369]
Not sure in which repository I should report this, so I also created https://github.com/rollup/rollup-plugin-babel/issues/297

When I use rollup-plugin-commonjs on a CommonJS module that contains an ES6 class that gets transpiled through rollup-plugin-babel, the CommonJS requires() and exports are no longer processed.

Here's a showcase for the issue: https://github.com/arendjr/rollup-commonjs-babel-issue

I had started by asking on StackOverflow (https://stackoverflow.com/questions/54256079/using-rollup-in-combination-with-babel-and-commonjs-plugins-doesnt-resolve-all), but I'm now convinced this is an issue, so I'm reporting here as well.

**Comment by arendjr** [comment]
As discussed in the related ticket, this is because Babel inserts an `import` statement for the class helpers after which the CommonJS plugin decides it shouldn't do anything anymore because it deems the module an ES module and it only wants to operate on CommonJS modules.

Knowing the backstory, it kinda makes sense now, but I do have to say it was quite unintuitive to me. Also, I would like to keep this issue open in order to at least consider adding an option that would allow the CommonJS plugin to work on ES modules. It would be quite valuable in situations where a codebase cannot migrate all at once and a mixture of ES modules and CommonJS needs to coexist for a while. If I'm not mistaken, Webpack and the React Native bundler allow to mix them as well.

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid.

We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets reopened and transferred to the new repo. :beer:

**Comment by QingLeiLi** [comment]
@shellscape  I think this issue should reopen, I just run into this.
When I put the babel plugin before commonjs plugin, some require call in the bundle will not processed, then when I put the babel plugin after that, commonjs plugin parse static class props will throw error, It is difficult to solve by the end user.
Maybe commonjs plugin could improve that.

**Comment by shellscape** [comment]
This sounds like a documentation issue more than anything. We'll transfer this issue and improve the documentation.
