### ISSUE TITLE
Can't use React hooks

### ISSUE THREAD

**Issue by screendriver** [rollup/rollup-plugin-commonjs#407]
I want to use [React hooks](https://reactjs.org/docs/hooks-intro.html) within my application that is bundled with rollup via

`import React, { useState } from 'react';`

Unfortunately I get the error

`Error: 'useState' is not exported by node_modules/react/index.js`

My `rollup.config.js` looks like this:

```js
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';

export default {
  input: 'target/index.js',
  output: {
    file: 'public/bundle.js',
    format: 'iife',
    sourcemap: true,
  },
  plugins: [
    resolve(),
    commonjs({
      include: 'node_modules/**',
      react: ['Component', 'createElement', 'createContext', 'useState'],
      'react-dom': ['render'],
    }),
    replace({
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
  ],
};
```

**Comment by TrySound** [comment]
Hi @screendriver Try this

```js
import react from 'react';
import reactDom from 'react-dom';

commonjs({
  namedExports: {
    react: Object.keys(react),
    'react-dom': Object.keys(reactDom)
  }
})
```

**Comment by screendriver** [comment]
Awesome. Thanks! 🎉

**Comment by funkybob** [comment]
After struggling with this same issue over the past couple of weeks trying to port a project from webpack to rollup, I'd really love to understand why this fails.

Given `module.exports = React` in the CJS bundle, doesn't that mean `import { foo } from 'react';` should be importing, effectively, `React.foo` ?

**Comment by eight04** [comment]
Nope. `module.exports = React` will be converted to `export default React`. This statement doesn't export a `foo` variable. You will get an import error when trying to `import {foo} from 'react'`.

To make it work, you have to configure the transformer i.e. the commonjs plugin to add an extra statement:
```js
export default React;
export const foo = React.foo;
```
See https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports

**Comment by funkybob** [comment]
Thanks! I've spent a couple of days flailing about trying to find any authoritative declaration of how that works -- exports vs. module.exports ; Life would be so much nicer if people would publish ESM, too :/

**Comment by bkulyk** [comment]
@TrySound works brilliantly, but I hate it.  I've wasted far too much time on this problem, thanks a ton.

**Comment by funkybob** [comment]
My current rollup has a series of `rollup-plugin-re` entries to convert broken imports into something more sane. e.g.:
```
{
  // ironically, this is the format FB seem to be planning to use in the next major release
  test: "import * as React from 'react';",
  replace: (_, imp) => `import React from 'react';`
},
{
  test: /import React, (\{.+\}) from 'react';/,
  replace: (_, imp) => `import React from 'react'; const ${imp} = React;`
},
{
  test: /import (\{.+\}) from 'react';/,
  replace: (_, imp) => `import React from 'react'; const ${imp} = React;`
},
```

I have 9 such entries, and have managed to get our sizeable codebase working. Note that it's not React that does this "wrong"; it's all 3rd party libs.

Coming from a language with more strict rules about importing, it sometimes amazes me the JS world works as well as it does...
