### ISSUE TITLE
Error: 'tslib' is imported as an external by tslib?commonjs-proxy, but is already an existing non-external module id.

### ISSUE THREAD

**Issue by themaskedavenger** [rollup/rollup-plugin-commonjs#413]
I'm trying to make an all-in bundled application that can run off of just 1 file. When I run rollup I get this error:

```Error: 'tslib' is imported as an external by tslib?commonjs-proxy, but is already an existing non-external module id.```

tslib is not imported directly by any of my application's code, so this is just a dependency within a dependency. Is there some flag to prevent this error? Also, what is the `?commonjs-proxy` there? Is this some kind of circular dependency?

Using typescript, resolve, commonjs, and json plugins.

**Comment by TrySound** [comment]
Please provide rollup config

**Comment by themaskedavenger** [comment]
Ah sorry, it's roughly this: ```
import commonjs from 'rollup-plugin-commonjs';
import json from 'rollup-plugin-json';
import nodeBuiltins from 'rollup-plugin-node-builtins';
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';

export default {
  input: 'src/runServer.ts',
  output: {
    file: 'dist/build/runServer.js',
    format: 'umd',
  },
  plugins: [
    nodeBuiltins(),
    typescript(),
    resolve(),
    commonjs(),
    json(),
  ],
};```

**Comment by themaskedavenger** [comment]
I have tried different formats to no avail

**Comment by TrySound** [comment]
Try to remove rollup-plugin-node-builtins

**Comment by GongT** [comment]
Typescript should after resolve.
----
When I use `rollup-plugin-ignore`, I got:
```
[src] (!) Unresolved dependencies
[src] https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
[src] empty_module (imported by empty_module?commonjs-proxy)
[src] [!] Error: 'empty_module' is imported as an external by empty_module?commonjs-proxy, but is already an existing non-external module id.
[src] Error: 'empty_module' is imported as an external by empty_module?commonjs-proxy, but is already an existing non-external module id.
[src]     at error (/data/DevelopmentRoot/canaan-creative/door/admin/app/node_modules/rollup/dist/rollup.js:10162:30)
[src]     at ModuleLoader.fetchResolvedDependency (/data/DevelopmentRoot/canaan-creative/door/admin/app/node_modules/rollup/dist/rollup.js:17226:24)
[src]     at ModuleLoader.<anonymous> (/data/DevelopmentRoot/canaan-creative/door/admin/app/node_modules/rollup/dist/rollup.js:17286:25)
[src]     at Generator.next (<anonymous>)
[src]     at fulfilled (/data/DevelopmentRoot/canaan-creative/door/admin/app/node_modules/rollup/dist/rollup.js:40:28)
```

**Comment by TrySound** [comment]
Why ignore plugin? What are you trying to achieve? Do you build for node or for browser?

**Comment by TrySound** [comment]
You can use rollup for that and prevent pollution runtime with this library.
```js
{
  resolveId(importee, importer) {
    if (importee === 'broken-lib') {
      return this.resolve(path.join(__dirname, './fixed-lib.js'), importer);
    }
  }
}
```

**Comment by themaskedavenger** [comment]
I've tried it without rollup-plugin-node-builtins, same error.

**Comment by themaskedavenger** [comment]
What does this error mean, exactly?!

**Comment by TrySound** [comment]
Could you create repo with the error you facing?

**Comment by shellscape** [comment]
Hey folks (this is a canned reply, but we mean it!). Thanks to everyone who participated in this issue. We're getting ready to move this plugin to a new home at https://github.com/rollup/plugins, and we have to do some spring cleaning of the issues to make that happen. We're going to close this one, but it doesn't mean that it's not still valid. We've got some time yet before the move while we resolve pending Pull Requests, so if this issue is still relevant, please @ me and I'll make sure it gets transferred to the new repo. :beer:
