### ISSUE TITLE
Evaluating conditional require delayed

### ISSUE THREAD

**Issue by yesmeck** [rollup/rollup-plugin-commonjs#424]
We came across a situation that there is a third party library require module conditionally.

```javascript
function foo() {
  if (env.production) {
    return require('./foo.production');
  }
  return require('./foo');
}
```

Now this plugin will hoist all requires to the top scope, which will lead both modules to be evaluated, but we want them to be evaluated conditionally. Can we evaluating conditional required module delayed？

**Comment by LeoYuan** [comment]
We ran into the same issue too.

Supposed solution:

Find those requires in conditional statement like `if / else if / switch case / conditional operator`, and wrap those module in a lazy execution mode, code as below:

```js
import getFooProduction from './foo.production-wrapper';
import getFoo from './foo-wrapper';

function foo() {
  if (env.production) {
    return getFooProduction();
  }
  return getFoo();
}
```

**Comment by LeoYuan** [comment]
I tried using { ignore: [ './foo.production', './foo' ] } to prevent transpiling  `conditional requires`,
BUT sadly, the ignore files will not be copied to dist folder, so an `Module Not Found` error would be thrown when try to load `./foo.production` / `./foo`.

I think this solution maybe better than that I supposed above, ignore specified modules & **copy those required modules to dist folder**

**Comment by eight04** [comment]
I think what we need is to run dead code elimination before running the commonjs plugin. Rollup already supports dead code elimination. Not sure if it is possible to extract the logic into a plugin.

Currently, I'm using the [re](https://www.npmjs.com/package/rollup-plugin-re) plugin to strip unwanted modules from the bundle i.e. replace the entire module with an empty string.

**Comment by yesmeck** [comment]
The conditions are determined at runtime, rollup-plugin-re won't work in my case.

**Comment by lukastaegert** [comment]
There is currently no way to translate a synchronous conditional require call to an ES module, which is required to make this work. Possible options:
- Write a plugin (or extend this plugin) to check for certain conditional require patterns where the target cannot be resolved and replace them with e.g. throwing an error (which would happen if you require something that is not there)
- Create two bundles of the dependency in question, one where the condition is true, one where it is false. Write a wrapper that dynamically imports the correct version using an asynchronous dynamic import

**Comment by yesmeck** [comment]
@lukastaegert  I see thanks for your reply.
