### ISSUE TITLE
"process" is undefined

### ISSUE THREAD

**Issue by nolanlawson** [rollup/rollup-plugin-commonjs#46]
A lot of Browserifiable/Webpackable modules use `process.browser` to check whether or not we're in "browser mode" vs "Node mode". It's unfortunate that this plugin doesn't define a global `process` anywhere, because this causes lots of modules to break when you try to import them in Rollup.

For example:

```
import lie from 'lie';
```

^ this fails because of `process.browser` switches ([these lines](https://github.com/calvinmetcalf/lie/blob/a8775403f13c24fb1ba2615b26b82e3fb7819767/lib/index.js#L13-L16)).

**Comment by calvinmetcalf** [comment]
probably could be fixed with this https://github.com/calvinmetcalf/rollup-plugin-node-globals

**Comment by nolanlawson** [comment]
You're right, this should be solved by another plugin. Amazing work!
