### ISSUE TITLE
ability to ignore global

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup-plugin-commonjs#48]
it would be nice to have an option to ignore 'global' for the purposes of determining whether something is a commonjs file.  As currently using it in an es6 module will cause it to be compiled (and thus erroring out) even if it's being dealt with somewhere else

**Comment by Rich-Harris** [comment]
Just discovered this and #50 were merged but never released – sorry, just released 3.0.0 with these changes. thanks!
