### ISSUE TITLE
improve global object

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup-plugin-commonjs#50]
currently it will fail if we are in a web worker or in an unknown situation in strict mode

compare what this module adds

```js
typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : this;
```
with what browserify adds

```js
typeof global !== "undefined" ? global : typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {}
```

how I'd recommend switching to the browserify version

**Comment by TrySound** [comment]
What is the reason for this order? I think `window` is the most unsafe case and should be processed first. `self` is a bit similar so should be the secod.

**Comment by calvinmetcalf** [comment]
I used a different ordering in the actual pull based on me thinking code was likely going to be run in a browser, node, or a web worker in that order
