### ISSUE TITLE
false positives for commonjs check

### ISSUE THREAD

**Issue by calvinmetcalf** [rollup/rollup-plugin-commonjs#53]
currently any mention of `require`, `module` and `exports` causes a module to be flagged as commonjs and in need of transpiling even if it's something like `var a=typeof require=="function"&&require;` (which is part of browserify bundles).  Might make sense to do a second, more in depth parse of the files to make sure it really is one.

**Comment by TrySound** [comment]
ref https://github.com/rollup/rollup-plugin-commonjs/issues/38

**Comment by calvinmetcalf** [comment]
yeah this may be a false positive on my part here

**Comment by calvinmetcalf** [comment]
wait no, there are certain things that will trigger a wrap including typeof foo checks and (ironically) the global check that uses global only if it's present

**Comment by Rich-Harris** [comment]
Just doing some housekeeping – is this still a live issue or can it be closed? `import` and `export` prevent a module from being treated as CommonJS, I don't *think* there are any other cases where a false positive would be truly problematic?

**Comment by calvinmetcalf** [comment]
This was opened on like v3 so I'll reopen if it's still an issue
