### ISSUE TITLE
Why check for `default` on commonjs modules?

### ISSUE THREAD

**Issue by maranomynet** [rollup/rollup-plugin-commonjs#58]
I'm curious:
Since CommonJS module's don't have the concept of an explicit "default" export...

Why does this:

```js
import foo from './_js/commonjs-module.js';

alert(foo.answer);
````

...result in this?

```js
var module$1 = __commonjs(function (module) {
  module.exports = {
    msg: 'This is a CommonJs module',
    answer: 42,
  };
});
var foo = (module$1 && typeof module$1 === 'object' && 'default' in module$1 ? module$1['default'] : module$1);

alert(foo.answer);
```

I mean, why not simply say  `var foo = module$1;` since this seems to be the inevitable end result every time anyway?

**Comment by maranomynet** [comment]
(moved from rollup/rollup-plugin-node-resolve#30)

**Comment by hisland** [comment]
I'm curious too, webpack depends on `obj.__esModule`, check use
`function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }`

rollup depends on `'default' in a` check use
`(a && typeof a === 'object' && 'default' in a ? a['default'] : a)`

**Comment by cssmagic** [comment]
I guess, its purpose is to be compatible with those "CommonJS modules" actually transformed from ES6 modules. We don't how the transformer treats default exporting of ES6 modules -- it might be converted to either `module.exports` (Babel5 style) or `exports.default` (Babel6 style).

**Comment by maranomynet** [comment]
Hmm... seems that such Babel6 modules aren't proper CommonJS modules in a sense that justifies adding special-casing for.

**Comment by alexlur** [comment]
By the way TypeScript does that too.
