### ISSUE TITLE
Fails when combined with babel and sourcemaps

### ISSUE THREAD

**Issue by Tokimon** [rollup/rollup-plugin-commonjs#67]
Hi I have trouble getting `rollup-plugin-commonjs` work with babel with`sourceMaps: true`.

Initially I was including it in a Karma build, that just kept failing when I included the plugin, so I made a Gulp build where I try to build the `.spec` files:

```javascript
const gulp = require('gulp');
const sourcemaps = require('gulp-sourcemaps');
const rename = require('gulp-rename');
const rollup = require('gulp-rollup');

const rollupBabel = require('rollup-plugin-babel');
const rollupNode = require('rollup-plugin-node-resolve');
const rollupCJS = require('rollup-plugin-commonjs');

gulp.task('spec', () => {
  gulp.src('test/*.spec.js')
    .pipe(rollup({
      sourceMap: true,
      format: 'cjs',
      exports: 'none',
      plugins: [
        rollupNode({ jsnext: true, main: true }),
        rollupCJS({ sourceMap: true }),
        rollupBabel({ presets: ['es2015-rollup'] })
      ],
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(rename((path) => { path.basename = path.basename.replace('.spec', ''); }))
    .pipe(gulp.dest('spec'));
});
```

This setup creates no files, so I have tried the following:
- Set `sourceMap: false` => it runs fine.
- Remove the `rollupCJS` from the plugin list and leave `sourceMap: true` => it runs just fine.
- Remove `rollupBabel` from the plugins list and leave `sourceMap: true` => it runs just fine.

**Comment by jacobmischka** [comment]
Have you tried the same configuration using either the JavaScript API or the command line tool? `gulp-rollup` is known to be problematic: https://github.com/rollup/rollup/wiki/Build-tools#gulp-usage

**Comment by Tokimon** [comment]
No I haven't. I will. Thanks for the reply.

**Comment by Tokimon** [comment]
Just to update: I have successfully made a build with the Rollup API and avoided gulp-rollup.
