### ISSUE TITLE
Unexpected Token Export

### ISSUE THREAD

**Issue by JeffreyWay** [rollup/rollup-plugin-commonjs#68]
Apologies if I'm missing something. I'm trying to convert some CommonJS code to ES6 so that I can use it with Rollup, but I keep getting an "Unexpected Token Export" error that points to a `export default main$1` line in the compiled file. If I remove it, things seem to work. Here's a basic example:

```js
// main.js

var thing = require('./ex');

alert(thing.message);
```

```js
// ex.js

module.exports = {
    message: 'Hello World'
};
```

Here's what that all compiles down to:

```js
// compiled.js

function __commonjs(fn, module) { return module = { exports: {} }, fn(module, module.exports), module.exports; }

var ex = __commonjs(function (module) {
module.exports = {
    message: 'Hello World'
};
});

var require$$0 = (ex && typeof ex === 'object' && 'default' in ex ? ex['default'] : ex);

var main = __commonjs(function (module) {
var thing = require$$0;

alert(thing.message);
});

var main$1 = (main && typeof main === 'object' && 'default' in main ? main['default'] : main);

export default main$1;
//# sourceMappingURL=main.js.map

```

That last "export" line causes an error, when I run the script in the browser: "*main.js:3 Uncaught SyntaxError: Unexpected token export*.

What am I missing here? I'm using Rollup with Gulp, so here's how I call it:

```js
rollup({ plugins: [buble(), commonjs()] })
```

Thanks! Any help would be greatly appreciated.

**Comment by eventualbuddha** [comment]
You need to set the output format to something that can run in the browser. Looks like you more guy want `iife`.

**Comment by eventualbuddha** [comment]
"might want", not "more guy want".

**Comment by JeffreyWay** [comment]
I must not be understanding something. I was under the impression that I wouldn't need to do that.

For example, in my `main.js` snippet above, if I change:

```
var thing = require('./ex');

alert(thing.message);
```

To:

```
import thing from './ex';

alert(thing.message);
```

...everything works perfectly in the browser.

**Comment by JeffreyWay** [comment]
Here's the main thing I need to do:

1. Take a `main.js` file that uses the CommonJS syntax to require modules.
2. Prep that for use with Rollup.
3. Have Rollup and Buble do their thing to prep it for general browser use.

**Comment by Victorystick** [comment]
@JeffreyWay The reason you should use the `iife` format when targeting browsers is that they don't currently support the `export default` syntax.
