### ISSUE TITLE
When the default export is a function, other exports are undefined

### ISSUE THREAD

**Issue by Ryan-McMillan** [rollup/rollup-plugin-commonjs#69]
I'm running into an error when importing redux, and am not sure if this is the right place to report it, but it's my best guess.

The commonjs version of redux code is exporting both a function(default), and another property.  
When importing using rollup, the function is there, but the property is undefined.
When importing using Browserify, it's returning the function with the property tacked onto it.

Here's what the code in question is doing:

main.js
```
var test = require("./test.js");

console.log(test.one); // undefined  -   expected:1
```

test.js
```
exports.one = 1;
exports.default = function(){};
```

**Comment by TrySound** [comment]
@Ryan-McMillan Try 3.2.0 release.
