### ISSUE TITLE
`require()`ing ES6 module in CommonJS module

### ISSUE THREAD

**Issue by jvilk** [rollup/rollup-plugin-commonjs#70]
I have an NPM dependency `A` that exposes an ES6 module via `jsnext:main`. I have another NPM dependency `B` that only exposes a CommonJS module. `B` depends on `A` using `require()`.

Expectation: `rollup-plugin-commonjs` detects that `A` resolves to an ES6 module, and inserts the following code.

```
import * as A from 'A';
```

Reality:

```
import A = 'A';
```

Result:

```
A does not export default (imported by B)
```

Any advice?

**Comment by TrySound** [comment]
@jvilk Hi! Try 3.2.0 please.
