### ISSUE TITLE
external jQuery with bundled jquery plugins breaks on runtime to a undefined default since v3.2+

### ISSUE THREAD

**Issue by zeitiger** [rollup/rollup-plugin-commonjs#85]
I observe that jquery.easing or jquery-ui, that are part of my bundle, breaks with a fresh rollup setup my `import $ from 'jquery';`, because the generator don't produce `$$1 = 'default' in $$1 ? $$1['default'] : $$1;`. Instead I get `var $$1__default = $$1['default'];` what is undefined. 

I tried to workaround with `import * as $ from 'jquery';` but than I get the error that I could not call a namespace 😫 

How I can prevent jquery will be detected as external module with namespace?

``` javascript
ExternalModule.prototype.traceExport = function traceExport ( name ) {

    if ( name !== 'default' && name !== '*' ) this.exportsNames = true;
    if ( name === '*' ) this.exportsNamespace = true;

    return this.declarations[ name ] || (
        this.declarations[ name ] = new ExternalDeclaration( this, name )
    );
};
```

``` javascript
    return bundle.externalModules
        .map( function (module) {
            if ( !module.declarations.default ) return null;

            if ( module.exportsNamespace ) {
                return ((bundle.varOrConst) + " " + (module.name) + "__default = " + (module.name) + "['default'];");
            }

            if ( module.exportsNames ) {
                return ((bundle.varOrConst) + " " + (module.name) + "__default = 'default' in " + (module.name) + " ? " + (module.name) + "['default'] : " + (module.name) + ";");
            }

            return ((module.name) + " = 'default' in " + (module.name) + " ? " + (module.name) + "['default'] : " + (module.name) + ";");
        })
        .filter( Boolean )
        .join( '\n' );
```

**Comment by zeitiger** [comment]
I boiled it down that this breaking changes came with version 3.2, 3.1 works fine. So I pin now my version to 3.1 and hope this issue will be fixed or it will be possible to define how external module will be handled e.g. that explicit say the default of jquery external is jquery be it self or something like that 😕

**Comment by Rich-Harris** [comment]
Sorry for the slow response. It looks like this is fixed in more recent versions (which have a more robust approach to interop) – I've put together a working repo [here](https://github.com/Rich-Harris/rollup-plugin-commonjs-issue-85) to demonstrate.

**Comment by Zverik** [comment]
Just came here to say thanks @Rich-Harris — it wasn't obvious that one needs commonjs plugin for using jquery, and your example helped me fix the config.
