### ISSUE TITLE
More patterns for named exports

### ISSUE THREAD

**Issue by arv** [rollup/rollup-plugin-commonjs#9]
I'm currently using https://www.npmjs.com/package/text-encoding which does:

```js
module.exports = {
  TextEncoder: encoding.TextEncoder,
  TextDecoder: encoding.TextDecoder,
};
```

And therefore the named exports are not identified:

```
Module .../node_modules/text-encoding/index.js does not export TextDecoder (imported by ...)
```

**Comment by Victorystick** [comment]
Tiny pieces of code like this should be easy to statically analyse and optimise. We should look into it.
